package com.vuelossanitarios.backend.api;

import com.vuelossanitarios.backend.domain.catalog.*;
import com.vuelossanitarios.backend.domain.person.CommanderProfile;
import com.vuelossanitarios.backend.repository.*;
import com.vuelossanitarios.backend.security.CurrentUser;
import com.vuelossanitarios.backend.service.AuditService;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
import java.util.*;

@RestController
@RequestMapping("/api/catalogs")
public class CatalogController {
 private final AircraftRepository aircraft; private final AirportRepository airports; private final FlightPriorityRepository priorities; private final ProvinceRepository provinces; private final LocalityRepository localities; private final UserRepository users; private final CommanderProfileRepository commanderProfiles; private final CancellationReasonRepository cancellationReasons; private final AuditService audit;
 public CatalogController(AircraftRepository a, AirportRepository ap, FlightPriorityRepository p, ProvinceRepository pr, LocalityRepository l, UserRepository u, CommanderProfileRepository cp, CancellationReasonRepository cr, AuditService au){aircraft=a;airports=ap;priorities=p;provinces=pr;localities=l;users=u;commanderProfiles=cp;cancellationReasons=cr;audit=au;}
 @GetMapping("/aircraft") @PreAuthorize("hasAnyRole('DTS','OPERACIONES','CENTRO_OPERACIONES','COMANDANTE')") public List<AircraftView> aircraft(){return aircraft.findAllWithCurrentAirportOrderByMatricula().stream().filter(x->Boolean.TRUE.equals(x.getActivo())).map(this::aircraftView).toList();}
 @GetMapping("/aircraft/admin") @PreAuthorize("hasRole('ADMINISTRADOR')") public List<AircraftView> adminAircraft(){return aircraft.findAllWithCurrentAirportOrderByMatricula().stream().map(this::aircraftView).toList();}
 @GetMapping("/provinces") @PreAuthorize("hasAnyRole('ADMINISTRADOR','DTS','OPERACIONES','CENTRO_OPERACIONES','COMANDANTE')") public List<ProvinceView> provinces(){return provinces.findByActivoTrueOrderByNombreAsc().stream().map(x->new ProvinceView(x.getId(),x.getCodigoOficial(),x.getNombre())).toList();}
 @GetMapping("/localities") @PreAuthorize("hasAnyRole('DTS','OPERACIONES','CENTRO_OPERACIONES','COMANDANTE')") public List<LocalityView> localities(@RequestParam UUID provinceId,@RequestParam(defaultValue="") String q){return localities.findTop50ByProvincia_IdAndActivoTrueAndNombreContainingIgnoreCaseOrderByNombreAsc(provinceId,q.trim()).stream().map(x->new LocalityView(x.getId(),x.getCodigoOficial(),x.getNombre(),x.getProvincia().getNombre())).toList();}
 @GetMapping("/airports") @PreAuthorize("hasAnyRole('ADMINISTRADOR','DTS','OPERACIONES','CENTRO_OPERACIONES','COMANDANTE')") public List<AirportView> airports(@RequestParam(required=false) UUID provinceId,@RequestParam(defaultValue="") String q){List<Airport> found=provinceId==null?airports.findAll().stream().filter(x->Boolean.TRUE.equals(x.getActivo())&&x.getNombre().toLowerCase(Locale.ROOT).contains(q.trim().toLowerCase(Locale.ROOT))).limit(50).toList():airports.findTop50ByActivoTrueAndProvinciaReferencialIdAndNombreContainingIgnoreCaseOrderByNombreAsc(provinceId,q.trim());return found.stream().map(x->new AirportView(x.getId(),x.getCodigoOaci(),x.getCodigoIata(),x.getNombre(),x.getCiudad(),x.getTipo())).toList();}
 @GetMapping("/priorities") @PreAuthorize("hasAnyRole('DTS','OPERACIONES','CENTRO_OPERACIONES','COMANDANTE')") public List<PriorityView> priorities(){return priorities.findAll().stream().filter(x->Boolean.TRUE.equals(x.getActivo())).sorted(Comparator.comparing(FlightPriority::getOrden)).map(x->new PriorityView(x.getCodigo(),x.getNombre())).toList();}
 @GetMapping("/cancellation-reasons") @PreAuthorize("hasAnyRole('DTS','OPERACIONES','CENTRO_OPERACIONES','COMANDANTE')") public List<CancellationReasonView> cancellationReasons(){return cancellationReasons.findByActivoTrueOrderByOrdenAsc().stream().map(x->new CancellationReasonView(x.getId(),x.getCodigo(),x.getNombre(),x.getCategoria(),x.getOrden())).toList();}
 @PostMapping("/aircraft") @PreAuthorize("hasRole('ADMINISTRADOR')") @Transactional public AircraftView createAircraft(@Valid @RequestBody AircraftRequest r,@AuthenticationPrincipal CurrentUser current){Aircraft x=new Aircraft();copy(r,x);aircraft.save(x);audit.record(null,actor(current),"AIRCRAFT",x.getId(),"CREATE",null,"{\"matricula\":\""+x.getMatricula()+"\"}");return aircraftView(x);}
 @PutMapping("/aircraft/{id}") @PreAuthorize("hasRole('ADMINISTRADOR')") @Transactional public AircraftView updateAircraft(@PathVariable UUID id,@Valid @RequestBody AircraftRequest r,@AuthenticationPrincipal CurrentUser current){Aircraft x=aircraft.findById(id).orElseThrow(()->new ApiException(org.springframework.http.HttpStatus.NOT_FOUND,"Aeronave inexistente"));String before="{\"activo\":"+x.getActivo()+",\"aeropuertoActualId\":"+json(x.getAeropuertoActual()==null?null:x.getAeropuertoActual().getId().toString())+"}";copy(r,x);audit.record(null,actor(current),"AIRCRAFT",x.getId(),"UPDATE",before,"{\"activo\":"+x.getActivo()+",\"aeropuertoActualId\":"+json(x.getAeropuertoActual().getId().toString())+"}");return aircraftView(x);}
 @PostMapping("/aircraft/{id}/active") @PreAuthorize("hasRole('ADMINISTRADOR')") @Transactional public AircraftView setAircraftActive(@PathVariable UUID id,@Valid @RequestBody ActiveRequest r,@AuthenticationPrincipal CurrentUser current){Aircraft x=aircraft.findById(id).orElseThrow(()->new ApiException(org.springframework.http.HttpStatus.NOT_FOUND,"Aeronave inexistente"));Boolean before=x.getActivo();x.setActivo(r.activo());audit.record(null,actor(current),"AIRCRAFT",x.getId(),"SET_ACTIVE","{\"activo\":"+before+"}","{\"activo\":"+x.getActivo()+"}");return aircraftView(x);}
 @PostMapping("/aircraft/{id}/location") @PreAuthorize("hasAnyRole('ADMINISTRADOR','OPERACIONES','CENTRO_OPERACIONES')") @Transactional public AircraftView moveAircraft(@PathVariable UUID id,@Valid @RequestBody LocationRequest r,@AuthenticationPrincipal CurrentUser current){Aircraft x=aircraft.lockById(id).orElseThrow(()->new ApiException(org.springframework.http.HttpStatus.NOT_FOUND,"Aeronave inexistente"));Airport old=x.getAeropuertoActual();Airport next=airports.findById(r.locationId()).filter(a->Boolean.TRUE.equals(a.getActivo())).orElseThrow(()->new ApiException(org.springframework.http.HttpStatus.BAD_REQUEST,"Seleccione un aeropuerto válido"));x.setAeropuertoActual(next);audit.record(null,actor(current),"AIRCRAFT",x.getId(),"MANUAL_LOCATION_CHANGE",old==null?null:"{\"aeropuertoActualId\":"+json(old.getId().toString())+"}","{\"aeropuertoActualId\":"+json(next.getId().toString())+"}");return aircraftView(x);}
 @PostMapping("/commanders/{id}/location") @PreAuthorize("hasAnyRole('ADMINISTRADOR','OPERACIONES','CENTRO_OPERACIONES')") @Transactional public CommanderLocationView moveCommander(@PathVariable UUID id,@Valid @RequestBody LocationRequest r,@AuthenticationPrincipal CurrentUser current){var target=users.findWithPersonById(id).orElseThrow(()->new ApiException(org.springframework.http.HttpStatus.NOT_FOUND,"Comandante inexistente"));CommanderProfile profile=target.getPerson().getCommanderProfile();if(profile==null)throw new ApiException(org.springframework.http.HttpStatus.BAD_REQUEST,"El usuario no tiene perfil de comandante");Province next=provinces.findById(r.locationId()).filter(Province::getActivo).orElseThrow(()->new ApiException(org.springframework.http.HttpStatus.BAD_REQUEST,"Seleccione una provincia válida"));Province old=profile.getProvinciaActual();profile.setProvinciaActual(next);audit.record(null,actor(current),"COMMANDER_PROFILE",target.getPerson().getId(),"MANUAL_LOCATION_CHANGE",old==null?null:"{\"provinciaActualId\":"+json(old.getId().toString())+"}","{\"provinciaActualId\":"+json(next.getId().toString())+"}");return new CommanderLocationView(target.getId(),next.getId(),next.getNombre());}
 @PostMapping("/airports") @PreAuthorize("hasRole('ADMINISTRADOR')") @Transactional public AirportView createAirport(@Valid @RequestBody AirportRequest r){Airport x=new Airport();x.setCodigoOaci(blank(r.codigoOaci()));x.setCodigoIata(blank(r.codigoIata()));x.setNombre(r.nombre());x.setCiudad(blank(r.ciudad()));x.setProvincia(blank(r.provincia()));x.setPais(r.pais()==null||r.pais().isBlank()?"Argentina":r.pais());airports.save(x);return new AirportView(x.getId(),x.getCodigoOaci(),x.getCodigoIata(),x.getNombre(),x.getCiudad(),x.getTipo());}
 private String blank(String value){return value==null||value.isBlank()?null:value.trim();}
 private void copy(AircraftRequest r,Aircraft x){x.setMatricula(r.matricula().trim());x.setModelo(r.modelo().trim());x.setTipo(r.tipo().trim());x.setCapacidadPacientes(r.capacidadPacientes());x.setCapacidadTripulacion(r.capacidadTripulacion());x.setEquipamientoMedico(blank(r.equipamientoMedico()));x.setActivo(r.activo()==null||r.activo());x.setAeropuertoActual(airports.findById(r.aeropuertoActualId()).filter(a->Boolean.TRUE.equals(a.getActivo())).orElseThrow(()->new ApiException(org.springframework.http.HttpStatus.BAD_REQUEST,"Seleccione un aeropuerto actual válido")));}
 private AircraftView aircraftView(Aircraft x){Airport a=x.getAeropuertoActual();return new AircraftView(x.getId(),x.getMatricula(),x.getModelo(),x.getTipo(),x.getCapacidadPacientes(),x.getCapacidadTripulacion(),x.getEquipamientoMedico(),Boolean.TRUE.equals(x.getActivo()),a==null?null:a.getId(),a==null?null:a.getNombre());}
 private com.vuelossanitarios.backend.domain.user.User actor(CurrentUser current){return users.findById(current.id()).orElseThrow(()->new ApiException(org.springframework.http.HttpStatus.NOT_FOUND,"Usuario inexistente"));}
 private String json(String value){return value==null?null:"\""+value+"\"";}
 public record AircraftRequest(@NotBlank @Size(max=20) String matricula,@NotBlank @Size(max=100) String modelo,@NotBlank @Size(max=50) String tipo,@NotNull @Min(1) Short capacidadPacientes,@NotNull @Min(1) Short capacidadTripulacion,@Size(max=10000) String equipamientoMedico,@NotNull UUID aeropuertoActualId,Boolean activo){}
 public record ActiveRequest(@NotNull Boolean activo){} public record LocationRequest(@NotNull UUID locationId){} public record CommanderLocationView(UUID comandanteId,UUID provinciaActualId,String provinciaActual){}
 public record AirportRequest(@Size(max=4) String codigoOaci,@Size(max=3) String codigoIata,@NotBlank @Size(max=150) String nombre,@Size(max=100) String ciudad,@Size(max=100) String provincia,@Size(max=100) String pais){}
 public record AircraftView(UUID id,String matricula,String modelo,String tipo,Short capacidadPacientes,Short capacidadTripulacion,String equipamientoMedico,boolean activo,UUID aeropuertoActualId,String aeropuertoActual){} public record ProvinceView(UUID id,String codigoOficial,String nombre){} public record LocalityView(UUID id,String codigoOficial,String nombre,String provincia){} public record AirportView(UUID id,String codigoOaci,String codigoIata,String nombre,String ciudad,String tipo){} public record PriorityView(String codigo,String nombre){} public record CancellationReasonView(UUID id,String codigo,String nombre,String categoria,Short orden){}
}
