package com.vuelossanitarios.backend.service;

import com.vuelossanitarios.backend.api.ApiException;
import com.vuelossanitarios.backend.api.dto.AuthDtos.*;
import com.vuelossanitarios.backend.domain.person.*;
import com.vuelossanitarios.backend.domain.user.*;
import com.vuelossanitarios.backend.repository.*;
import com.vuelossanitarios.backend.security.JwtService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.*;
import org.springframework.http.HttpStatus;
import org.springframework.security.crypto.password.PasswordEncoder;
import java.time.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

class AuthServiceTest {
 @Mock UserRepository users; @Mock PersonRepository persons; @Mock RoleRepository roles; @Mock UserRoleRepository userRoles; @Mock EmailContactRepository emails; @Mock PhoneContactRepository phones; @Mock AccountActivationRepository activations; @Mock CommanderProfileRepository commanderProfiles; @Mock AuditService audit; @Mock PasswordEncoder encoder; @Mock JwtService jwt;
 AuthService service;
 @BeforeEach void init(){MockitoAnnotations.openMocks(this);service=new AuthService(users,persons,roles,userRoles,emails,phones,activations,commanderProfiles,audit,encoder,jwt);when(roles.findByCodigo(anyString())).thenAnswer(x->Optional.of(role(x.getArgument(0))));when(encoder.encode(anyString())).thenAnswer(x->"hash:"+x.getArgument(0));}
 CreatePendingUserRequest request(Set<String> role,List<ContactRequest> es,List<PhoneRequest> ps){return new CreatePendingUserRequest("Ana","Pérez","123",null,role.contains("COMANDANTE")?"LIC1":null,role,es,ps);}
 List<ContactRequest> email(){return List.of(new ContactRequest("ana@example.test","PERSONAL"));} List<PhoneRequest> phone(){return List.of(new PhoneRequest("3815555555","PERSONAL"));}
 @Test void createPendingRequiresEmail(){ApiException e=assertThrows(ApiException.class,()->service.createPending(request(Set.of("DTS"),List.of(),phone()),null));assertEquals(HttpStatus.BAD_REQUEST,e.status());}
 @Test void createPendingRequiresPhone(){assertThrows(ApiException.class,()->service.createPending(request(Set.of("DTS"),email(),List.of()),null));}
 @Test void createPendingRejectsDuplicateDni(){when(persons.existsByDni("123")).thenReturn(true);ApiException e=assertThrows(ApiException.class,()->service.createPending(request(Set.of("DTS"),email(),phone()),null));assertEquals(HttpStatus.CONFLICT,e.status());}
 @Test void administratorCanCombineDts(){prepareSaves();assertNotNull(service.createPending(request(Set.of("ADMINISTRADOR","DTS"),email(),phone()),null).codigo());}
 @Test void administratorCanCombineOperations(){prepareSaves();assertNotNull(service.createPending(request(Set.of("ADMINISTRADOR","CENTRO_OPERACIONES"),email(),phone()),null).codigo());}
 @Test void administratorCanCombineCommanderWithLicense(){prepareSaves();assertNotNull(service.createPending(request(Set.of("ADMINISTRADOR","COMANDANTE"),email(),phone()),null).codigo());}
 @Test void commanderWithoutLicenseIsRejected(){CreatePendingUserRequest withoutLicense=new CreatePendingUserRequest("Ana","Pérez","123",null,null,Set.of("COMANDANTE"),email(),phone());ApiException e=assertThrows(ApiException.class,()->service.createPending(withoutLicense,null));assertEquals(HttpStatus.BAD_REQUEST,e.status());}
 @Test void commanderWithLicenseIsAccepted(){prepareSaves();assertNotNull(service.createPending(request(Set.of("COMANDANTE"),email(),phone()),null).codigo());}
 @Test void commanderProfileIsCanonicalAndAudited(){prepareSaves();CreatePendingUserRequest r=new CreatePendingUserRequest("Ana","Pérez","47.355.303",null," abc123 ",Set.of("COMANDANTE"),email(),phone());service.createPending(r,null);ArgumentCaptor<CommanderProfile> profile=ArgumentCaptor.forClass(CommanderProfile.class);verify(commanderProfiles).save(profile.capture());assertEquals("ABC123",profile.getValue().getLicenseNumber());verify(audit).record(isNull(),isNull(),eq("COMMANDER_PROFILE"),any(),eq("CREATE"),isNull(),contains("profileCreated"));}
 @Test void formattedDniIsStoredCanonicalAndDuplicateUsesSameKey(){prepareSaves();CreatePendingUserRequest formatted=new CreatePendingUserRequest("Ana","Pérez","47.355.303",null,null,Set.of("DTS"),email(),phone());service.createPending(formatted,null);ArgumentCaptor<Person> saved=ArgumentCaptor.forClass(Person.class);verify(persons).save(saved.capture());assertEquals("47355303",saved.getValue().getDni());when(persons.existsByDni("47355303")).thenReturn(true);CreatePendingUserRequest duplicate=new CreatePendingUserRequest("Beto","López","47 355 303",null,null,Set.of("DTS"),email(),phone());assertThrows(ApiException.class,()->service.createPending(duplicate,null));}
 @Test void operationalRolesCanCombine(){when(persons.save(any())).thenAnswer(x->{((Person)x.getArgument(0)).setId(UUID.randomUUID());return x.getArgument(0);});when(users.save(any())).thenAnswer(x->{((User)x.getArgument(0)).setId(UUID.randomUUID());return x.getArgument(0);});ActivationCodeResponse response=service.createPending(request(Set.of("COMANDANTE","OPERACIONES"),email(),phone()),null);assertNotNull(response.codigo());verify(userRoles,times(2)).save(any());}
 @Test void multiplePendingPeopleCanBeCreated(){prepareSaves();ActivationCodeResponse first=service.createPending(request(Set.of("OPERACIONES"),email(),phone()),null);ActivationCodeResponse second=service.createPending(new CreatePendingUserRequest("Beto","López","456",null,null,Set.of("OPERACIONES"),email(),phone()),null);assertNotEquals(first.codigo(),second.codigo());verify(persons,times(2)).save(any(Person.class));verify(users,times(2)).save(any(User.class));}
 @Test void generatedActivationIsNeverStoredPlain(){when(persons.save(any())).thenAnswer(x->{((Person)x.getArgument(0)).setId(UUID.randomUUID());return x.getArgument(0);});when(users.save(any())).thenAnswer(x->{((User)x.getArgument(0)).setId(UUID.randomUUID());return x.getArgument(0);});ActivationCodeResponse response=service.createPending(request(Set.of("DTS"),email(),phone()),null);ArgumentCaptor<AccountActivation> captor=ArgumentCaptor.forClass(AccountActivation.class);verify(activations).save(captor.capture());assertNotEquals(response.codigo(),captor.getValue().getTokenHash());assertEquals(24,Duration.between(captor.getValue().getCreatedAt(),captor.getValue().getExpiresAt()).toHours());}
 @Test void pendingCreationReturnsOneTimeCodeWhoseHashIsPersisted(){prepareSaves();ActivationCodeResponse response=service.createPending(request(Set.of("DTS"),email(),phone()),null);ArgumentCaptor<AccountActivation> captor=ArgumentCaptor.forClass(AccountActivation.class);verify(activations).save(captor.capture());assertNotNull(response.codigo());assertFalse(response.codigo().isBlank());assertNotEquals(response.codigo(),captor.getValue().getTokenHash());assertEquals("hash:"+response.codigo(),captor.getValue().getTokenHash());}
 private AccountActivation pending(String hash, LocalDateTime expires){Person p=new Person();p.setDni("123");p.setId(UUID.randomUUID());User u=new User();u.setId(UUID.randomUUID());u.setPerson(p);u.setActivo(true);u.setEstadoCuenta("PENDIENTE_ACTIVACION");AccountActivation a=new AccountActivation();a.setUser(u);a.setTokenHash(hash);a.setCreatedAt(LocalDateTime.now().minusHours(1));a.setExpiresAt(expires);return a;}
 @Test void correctActivationSetsUsernameAndHashedPassword(){AccountActivation a=pending("stored",LocalDateTime.now().plusHours(1));when(activations.findOpenByDni("123")).thenReturn(List.of(a));when(encoder.matches("code","stored")).thenReturn(true);service.activate(new ActivateAccountRequest("123","code","ana","NewPassword123","NewPassword123"));assertEquals("ACTIVO",a.getUser().getEstadoCuenta());assertEquals("ana",a.getUser().getUsername());assertEquals("hash:NewPassword123",a.getUser().getPasswordHash());assertNotNull(a.getUsedAt());}
 @Test void activationAcceptsFormattedCanonicalDni(){AccountActivation a=pending("stored",LocalDateTime.now().plusHours(1));a.getUser().getPerson().setDni("47355303");when(activations.findOpenByDni("47355303")).thenReturn(List.of(a));when(encoder.matches("code","stored")).thenReturn(true);service.activate(new ActivateAccountRequest("47.355.303","code","ana","NewPassword123","NewPassword123"));assertEquals("ACTIVO",a.getUser().getEstadoCuenta());}
 @Test void invalidCodeIsRejected(){AccountActivation a=pending("stored",LocalDateTime.now().plusHours(1));when(activations.findOpenByDni("123")).thenReturn(List.of(a));when(encoder.matches("bad","stored")).thenReturn(false);assertThrows(ApiException.class,()->service.activate(new ActivateAccountRequest("123","bad","ana","NewPassword123","NewPassword123")));}
 @Test void expiredCodeIsRejectedWithoutWaiting(){AccountActivation a=pending("stored",LocalDateTime.now().minusNanos(1));when(activations.findOpenByDni("123")).thenReturn(List.of(a));when(encoder.matches(anyString(),anyString())).thenReturn(true);assertThrows(ApiException.class,()->service.activate(new ActivateAccountRequest("123","code","ana","NewPassword123","NewPassword123")));}
 @Test void reusedCodeReportsAnAlreadyActivatedAccount(){User u=pending("stored",LocalDateTime.now().plusHours(1)).getUser();u.setEstadoCuenta("ACTIVO");when(activations.findOpenByDni("123")).thenReturn(List.of());when(users.findWithPersonByDni("123")).thenReturn(Optional.of(u));ApiException e=assertThrows(ApiException.class,()->service.activate(new ActivateAccountRequest("123","code","ana","NewPassword123","NewPassword123")));assertEquals(HttpStatus.CONFLICT,e.status());assertEquals("La cuenta ya está activada",e.getMessage());}
 @Test void duplicateUsernameIsRejected(){AccountActivation a=pending("stored",LocalDateTime.now().plusHours(1));when(activations.findOpenByDni("123")).thenReturn(List.of(a));when(encoder.matches(anyString(),anyString())).thenReturn(true);when(users.existsByUsername("ana")).thenReturn(true);ApiException e=assertThrows(ApiException.class,()->service.activate(new ActivateAccountRequest("123","code","ana","NewPassword123","NewPassword123")));assertEquals(HttpStatus.CONFLICT,e.status());}
 @Test void regenerationInvalidatesOldCode(){User u=pending("x",LocalDateTime.now().plusHours(1)).getUser();when(users.findWithPersonById(u.getId())).thenReturn(Optional.of(u));AccountActivation old=pending("old",LocalDateTime.now().plusHours(1));old.setUser(u);when(activations.findOpenByUserId(u.getId())).thenReturn(List.of(old));service.regenerate(u.getId(),null);assertNotNull(old.getUsedAt());verify(activations).save(any(AccountActivation.class));}
 @Test void temporaryPasswordRequiresChangeAndOwnChangeClearsIt(){User u=pending("x",LocalDateTime.now().plusHours(1)).getUser();u.setUsername("ana");u.setPasswordHash("old");when(users.findWithPersonById(u.getId())).thenReturn(Optional.of(u));service.setTemporaryPassword(u.getId(),new TemporaryPasswordRequest("Temporary123"));assertTrue(u.getDebeCambiarContrasena());when(encoder.matches("Temporary123","hash:Temporary123")).thenReturn(true);service.changePassword(u.getId(),new ChangePasswordRequest("Temporary123","Permanent123","Permanent123"));assertFalse(u.getDebeCambiarContrasena());assertEquals("hash:Permanent123",u.getPasswordHash());}
 @Test void administratorCannotEditOwnRoles(){User admin=existingUser("ADMINISTRADOR");when(users.findWithPersonById(admin.getId())).thenReturn(Optional.of(admin));ApiException e=assertThrows(ApiException.class,()->service.updateUser(admin.getId(),update(Set.of("DTS"),true,null),admin.getId()));assertEquals(HttpStatus.FORBIDDEN,e.status());verify(users,never()).lockActiveAdministrators();}
 @Test void administratorCanEditAnotherAdministratorWhenAnotherActiveRemains(){User target=existingUser("ADMINISTRADOR");User other=existingUser("ADMINISTRADOR");when(users.findWithPersonById(target.getId())).thenReturn(Optional.of(target));when(users.lockActiveAdministrators()).thenReturn(List.of(target,other));service.updateUser(target.getId(),update(Set.of("DTS"),true,null),UUID.randomUUID());verify(users).lockActiveAdministrators();verify(audit).record(isNull(),isNull(),eq("USER_ROLE"),eq(target.getId()),eq("UPDATE"),any(),any());}
 @Test void onlyActiveAdministratorCannotBeDeactivatedOrLoseRole(){User target=existingUser("ADMINISTRADOR");when(users.findWithPersonById(target.getId())).thenReturn(Optional.of(target));when(users.lockActiveAdministrators()).thenReturn(List.of(target));assertThrows(ApiException.class,()->service.updateUser(target.getId(),update(Set.of("ADMINISTRADOR"),false,null),UUID.randomUUID()));assertThrows(ApiException.class,()->service.updateUser(target.getId(),update(Set.of("DTS"),true,null),UUID.randomUUID()));verify(users,times(2)).lockActiveAdministrators();}
 @Test void commanderRoleRemovalKeepsProfileAndReassignmentReusesIt(){User target=existingUser("COMANDANTE");CommanderProfile profile=new CommanderProfile();profile.setPerson(target.getPerson());profile.setLicenseNumber("ABC123");target.getPerson().setCommanderProfile(profile);when(users.findWithPersonById(target.getId())).thenReturn(Optional.of(target));service.updateUser(target.getId(),update(Set.of("DTS"),true,null),UUID.randomUUID());assertSame(profile,target.getPerson().getCommanderProfile());target.setUserRoles(new HashSet<>(Set.of(new UserRole(target,role("DTS")))));service.updateUser(target.getId(),update(Set.of("COMANDANTE"),true," ABC123 "),UUID.randomUUID());verify(commanderProfiles,never()).save(any());verify(audit).record(isNull(),isNull(),eq("USER_ROLE"),eq(target.getId()),eq("ASSIGN_COMMANDER"),isNull(),any());}
 @Test void administratorCanChangeCommanderLicenseAndItIsAudited(){User target=existingUser("COMANDANTE");CommanderProfile profile=new CommanderProfile();profile.setPerson(target.getPerson());profile.setLicenseNumber("ABC123");target.getPerson().setCommanderProfile(profile);when(users.findWithPersonById(target.getId())).thenReturn(Optional.of(target));service.updateUser(target.getId(),update(Set.of("COMANDANTE"),true,"xyz999"),UUID.randomUUID());assertEquals("XYZ999",profile.getLicenseNumber());verify(audit).record(isNull(),isNull(),eq("COMMANDER_PROFILE"),eq(target.getPerson().getId()),eq("UPDATE_LICENSE"),any(),any());}
 private Role role(String code){Role role=new Role();role.setCodigo(code);role.setActivo(true);return role;}
 private User existingUser(String code){Person p=new Person();p.setId(UUID.randomUUID());p.setNombre("Ana");p.setApellido("Pérez");User u=new User();u.setId(UUID.randomUUID());u.setPerson(p);u.setUsername("ana"+u.getId());u.setActivo(true);u.setEstadoCuenta("ACTIVO");u.setUserRoles(new HashSet<>(Set.of(new UserRole(u,role(code)))));return u;}
 private UpdateUserRequest update(Set<String> roles,boolean active,String license){return new UpdateUserRequest("Ana","Pérez",null,license,roles,active);}
 private void prepareSaves(){when(persons.save(any())).thenAnswer(x->{((Person)x.getArgument(0)).setId(UUID.randomUUID());return x.getArgument(0);});when(users.save(any())).thenAnswer(x->{((User)x.getArgument(0)).setId(UUID.randomUUID());return x.getArgument(0);});}
}
