package com.vuelossanitarios.backend.service;

import com.vuelossanitarios.backend.api.ApiException;
import com.vuelossanitarios.backend.api.dto.FlightDtos.*;
import com.vuelossanitarios.backend.domain.catalog.*;
import com.vuelossanitarios.backend.domain.flight.*;
import com.vuelossanitarios.backend.domain.patient.Patient;
import com.vuelossanitarios.backend.domain.person.*;
import com.vuelossanitarios.backend.domain.user.*;
import com.vuelossanitarios.backend.repository.*;
import java.time.LocalDateTime;
import java.util.*;
import org.junit.jupiter.api.*;
import org.mockito.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

class FlightServiceTest {
 @Mock FlightRepository flights; @Mock PatientRepository patients; @Mock UserRepository users; @Mock FlightStatusRepository statuses; @Mock FlightPriorityRepository priorities; @Mock AircraftRepository aircraft; @Mock AirportRepository airports; @Mock LocalityRepository localities; @Mock CrewRoleRepository crewRoles; @Mock FlightCrewRepository crews; @Mock FlightMedicalInfoRepository medical; @Mock FlightFinalReportRepository reports; @Mock FlightScheduleNegotiationRepository negotiations; @Mock AuditService audit; @Mock FlightAuthorizationService access; @Mock NotificationService notifications; @Mock FlightUrgencyPolicy urgency; @Mock FinalReportWorkflowService workflow; @Mock CommanderReportAccessService commanderAccess;
 FlightService service; User operations, commander; Patient patient;
 @BeforeEach void init(){MockitoAnnotations.openMocks(this);service=new FlightService(flights,patients,users,statuses,priorities,aircraft,airports,localities,crewRoles,crews,medical,reports,negotiations,audit,access,notifications,urgency,workflow,commanderAccess);operations=user("op",Set.of("CENTRO_OPERACIONES"),false);commander=user("cmd",Set.of("COMANDANTE","CENTRO_OPERACIONES"),true);patient=new Patient();patient.setId(UUID.randomUUID());Person patientPerson=new Person();patientPerson.setNombre("Paciente");patientPerson.setApellido("Prueba");patient.setPerson(patientPerson);when(users.findById(operations.getId())).thenReturn(Optional.of(operations));when(users.findById(commander.getId())).thenReturn(Optional.of(commander));when(users.findWithRolesByUsername("op")).thenReturn(Optional.of(operations));when(users.findWithRolesByUsername("cmd")).thenReturn(Optional.of(commander));when(statuses.findByCodigo(anyString())).thenAnswer(i->Optional.of(status(i.getArgument(0))));when(priorities.findByCodigoAndActivoTrue(anyString())).thenAnswer(i->Optional.of(priority(i.getArgument(0))));}
 @Test void dtsCanCreateSolicitadoWithOfficialLocalities(){User dts=user("dts",Set.of("DTS"),false);Locality origin=locality("San Miguel de Tucumán","Tucumán"),destination=locality("Salta","Salta");when(users.findById(dts.getId())).thenReturn(Optional.of(dts));when(patients.findById(patient.getId())).thenReturn(Optional.of(patient));when(localities.findByIdAndActivoTrue(origin.getId())).thenReturn(Optional.of(origin));when(localities.findByIdAndActivoTrue(destination.getId())).thenReturn(Optional.of(destination));when(flights.save(any())).thenAnswer(i->{Flight f=i.getArgument(0);f.setId(UUID.randomUUID());return f;});FlightView created=service.create(new CreateFlight(patient.getId(),origin.getId(),destination.getId(),"ALTA","Traslado",LocalDateTime.now().plusDays(3),false,null,null,new Medical("Diagnóstico","ESTABLE",true,"Oxígeno")),dts.getId());assertEquals("SOLICITADO",created.estado());assertEquals("San Miguel de Tucumán",created.origen().nombre());verify(medical).save(any(FlightMedicalInfo.class));}
 @Test void dtsRejectsUnknownOrInactiveOrigin(){User dts=user("dts",Set.of("DTS"),false);UUID unknown=UUID.randomUUID();when(users.findById(dts.getId())).thenReturn(Optional.of(dts));when(patients.findById(patient.getId())).thenReturn(Optional.of(patient));when(localities.findByIdAndActivoTrue(unknown)).thenReturn(Optional.empty());ApiException error=assertThrows(ApiException.class,()->service.create(new CreateFlight(patient.getId(),unknown,UUID.randomUUID(),"ALTA","Traslado",LocalDateTime.now().plusDays(3),false,null,null,new Medical(null,"ESTABLE",false,null)),dts.getId()));assertEquals(400,error.status().value());assertEquals("Seleccione una localidad de origen válida.",error.getMessage());}
 @Test void operationsCenterCanApprovePendingOnlyOnce(){Flight f=flight("SOLICITADO");when(flights.lockById(f.getId())).thenReturn(Optional.of(f));assertEquals("APROBADO",service.evaluate(f.getId(),new Evaluation(true,null,"ALTA"),operations.getId()).estado());ApiException error=assertThrows(ApiException.class,()->service.evaluate(f.getId(),new Evaluation(true,null,"ALTA"),operations.getId()));assertTrue(error.getMessage().contains("Transición no permitida"));}
 @Test void counterproposalAcceptedByItsDtsOwnerFixesTheNewDeparture(){User dts=user("dts",Set.of("DTS"),false);Flight f=flight("SOLICITADO");f.setSolicitadoPor(dts);LocalDateTime proposed=f.getFechaSolicitada().plusHours(2);FlightScheduleNegotiation event=new FlightScheduleNegotiation();event.setTipo("CO_CONTRAPROPUESTA");event.setFechaHoraPropuesta(proposed);when(users.findById(dts.getId())).thenReturn(Optional.of(dts));when(users.findWithRolesByUsername("dts")).thenReturn(Optional.of(dts));when(flights.lockById(f.getId())).thenReturn(Optional.of(f));service.counterproposal(f.getId(),new CounterProposal(proposed,"Sin aeronave disponible"),operations.getId());when(negotiations.findByFlightIdOrderByFechaOcurrenciaAsc(f.getId())).thenReturn(List.of(event));service.respondToCounterproposal(f.getId(),new NegotiationResponse(true,null),dts.getId());assertEquals("APROBADO",f.getStatus().getCodigo());assertEquals(proposed,f.getFechaPlanificadaSalida());}
 @Test void resourceAssignmentIsRejectedBeforeTheScheduleIsFixed(){Flight f=flight("SOLICITADO");when(flights.lockById(f.getId())).thenReturn(Optional.of(f));ApiException error=assertThrows(ApiException.class,()->service.assign(f.getId(),new AssignResources(UUID.randomUUID(),commander.getId()),operations.getId()));assertTrue(error.getMessage().contains("Transición no permitida"));}
 @Test void commanderFromAnotherProvinceCannotBeAssigned(){Flight f=flight("APROBADO");f.setFechaPlanificadaSalida(LocalDateTime.now().plusDays(3));Airport airport=new Airport();airport.setId(UUID.randomUUID());airport.setActivo(true);airport.setProvinciaReferencial(f.getLocalidadOrigenSolicitada().getProvincia());Aircraft plane=new Aircraft();plane.setId(UUID.randomUUID());plane.setActivo(true);plane.setAeropuertoActual(airport);Province other=new Province();other.setId(UUID.randomUUID());other.setNombre("Otra");commander.getPerson().getCommanderProfile().setProvinciaActual(other);when(flights.lockById(f.getId())).thenReturn(Optional.of(f));when(aircraft.lockById(plane.getId())).thenReturn(Optional.of(plane));ApiException error=assertThrows(ApiException.class,()->service.assign(f.getId(),new AssignResources(plane.getId(),commander.getId()),operations.getId()));assertTrue(error.getMessage().contains("provincia de origen"));}
 @Test void rejectionRequiresMeaningfulReason(){Flight f=flight("SOLICITADO");when(flights.lockById(f.getId())).thenReturn(Optional.of(f));assertThrows(ApiException.class,()->service.evaluate(f.getId(),new Evaluation(false,"   ",null),operations.getId()));assertEquals("SOLICITADO",f.getStatus().getCodigo());service.evaluate(f.getId(),new Evaluation(false,"No hay disponibilidad",null),operations.getId());assertEquals("CANCELADO",f.getStatus().getCodigo());assertEquals("No hay disponibilidad",f.getMotivoCancelacion());}
 @Test void operationsCenterCanAssignActiveLicensedMultiRoleCommanderAndAircraft(){Flight f=flight("APROBADO");Airport origin=new Airport();origin.setId(UUID.randomUUID());origin.setActivo(true);origin.setProvinciaReferencial(f.getLocalidadOrigenSolicitada().getProvincia());Airport destination=new Airport();destination.setId(UUID.randomUUID());destination.setActivo(true);destination.setProvinciaReferencial(f.getLocalidadDestinoSolicitada().getProvincia());f.setFechaPlanificadaSalida(LocalDateTime.now().plusDays(2));Aircraft plane=new Aircraft();plane.setId(UUID.randomUUID());plane.setActivo(true);plane.setAeropuertoActual(origin);commander.getPerson().getCommanderProfile().setProvinciaActual(f.getLocalidadOrigenSolicitada().getProvincia());CrewRole role=new CrewRole();role.setCodigo("COMANDANTE");when(flights.lockById(f.getId())).thenReturn(Optional.of(f));when(aircraft.lockById(plane.getId())).thenReturn(Optional.of(plane));when(flights.activeAircraftAssignments(eq(plane.getId()),any())).thenReturn(List.of());when(crewRoles.findByCodigo("COMANDANTE")).thenReturn(Optional.of(role));when(crews.existsByFlightIdAndUserId(f.getId(),commander.getId())).thenReturn(false);service.assign(f.getId(),new AssignResources(plane.getId(),commander.getId()),operations.getId());assertSame(plane,f.getAircraft());assertSame(commander,f.getComandante());assertEquals("PLANIFICADO",f.getStatus().getCodigo());verify(crews).save(any(FlightCrew.class));verify(notifications).create(eq(commander),eq(f),anyString(),anyString());}
 @Test void availabilityOnlyReturnsAircraftInTheRequestedOriginProvinceAndNotInFlight(){Flight f=flight("APROBADO");Airport origin=new Airport();origin.setId(UUID.randomUUID());origin.setNombre("Neuquén");origin.setProvinciaReferencial(f.getLocalidadOrigenSolicitada().getProvincia());Aircraft free=new Aircraft();free.setId(UUID.randomUUID());free.setMatricula("LV-LIBRE");free.setModelo("King Air");free.setTipo("ALA_FIJA");free.setAeropuertoActual(origin);Aircraft flying=new Aircraft();flying.setId(UUID.randomUUID());flying.setMatricula("LV-RESERVA");flying.setModelo("Learjet");flying.setTipo("ALA_FIJA");flying.setAeropuertoActual(origin);when(flights.findById(f.getId())).thenReturn(Optional.of(f));when(aircraft.findActiveLocatedInProvince(f.getLocalidadOrigenSolicitada().getProvincia().getId())).thenReturn(List.of(free,flying));when(flights.activeAircraftAssignments(free.getId(),List.of("EN_CURSO"))).thenReturn(List.of());when(flights.activeAircraftAssignments(flying.getId(),List.of("EN_CURSO"))).thenReturn(List.of(flight("EN_CURSO")));var available=service.availableAircraft(f.getId(),operations.getId());assertEquals(1,available.size());assertEquals("LV-LIBRE",available.getFirst().matricula());}
 private Flight flight(String state){Flight f=new Flight();f.setId(UUID.randomUUID());f.setCodigo("VS-TEST");f.setPatient(patient);f.setStatus(status(state));f.setPriority(priority("ALTA"));f.setSolicitadoPor(operations);f.setFechaSolicitada(LocalDateTime.now().plusDays(3));f.setLocalidadOrigenSolicitada(locality("Origen","Tucumán"));f.setLocalidadDestinoSolicitada(locality("Destino","Salta"));return f;}
 private Locality locality(String name,String provinceName){Province province=new Province();province.setId(UUID.randomUUID());province.setNombre(provinceName);Locality locality=new Locality();locality.setId(UUID.randomUUID());locality.setNombre(name);locality.setProvincia(province);locality.setActivo(true);return locality;}
 private User user(String username,Set<String> roles,boolean profile){Person p=new Person();p.setId(UUID.randomUUID());p.setNombre("Ana");p.setApellido("Pérez");if(profile){CommanderProfile cp=new CommanderProfile();cp.setPerson(p);cp.setLicenseNumber("LIC-123");p.setCommanderProfile(cp);}User u=new User();u.setId(UUID.randomUUID());u.setUsername(username);u.setPerson(p);u.setActivo(true);u.setEstadoCuenta("ACTIVO");Set<UserRole> assigned=new HashSet<>();for(String code:roles){Role r=new Role();r.setCodigo(code);assigned.add(new UserRole(u,r));}u.setUserRoles(assigned);return u;}
 private FlightStatus status(String code){FlightStatus s=new FlightStatus();s.setCodigo(code);s.setNombre(code);return s;} private FlightPriority priority(String code){FlightPriority p=new FlightPriority();p.setCodigo(code);return p;}
}
