package com.vuelossanitarios.backend.service;
import com.vuelossanitarios.backend.api.ApiException;
import com.vuelossanitarios.backend.api.dto.AuthDtos.*;
import com.vuelossanitarios.backend.domain.person.*;
import com.vuelossanitarios.backend.domain.user.*;
import com.vuelossanitarios.backend.repository.*;
import com.vuelossanitarios.backend.security.*;
import org.springframework.http.HttpStatus;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.security.SecureRandom;
import java.time.*;
import java.util.*;

@Service public class AuthService {
 private final UserRepository users; private final PersonRepository persons; private final RoleRepository roles; private final UserRoleRepository userRoles; private final EmailContactRepository emails; private final PhoneContactRepository phones; private final AccountActivationRepository activations; private final CommanderProfileRepository commanderProfiles; private final FlightRepository flights; private final FlightCrewRepository flightCrew; private final AuditService audit; private final PasswordEncoder encoder; private final JwtService jwt; private final SecureRandom random=new SecureRandom();
 @org.springframework.beans.factory.annotation.Autowired public AuthService(UserRepository u,PersonRepository p,RoleRepository r,UserRoleRepository ur,EmailContactRepository e,PhoneContactRepository ph,AccountActivationRepository a,CommanderProfileRepository cp,FlightRepository f,FlightCrewRepository fc,AuditService au,PasswordEncoder pe,JwtService j){users=u;persons=p;roles=r;userRoles=ur;emails=e;phones=ph;activations=a;commanderProfiles=cp;flights=f;flightCrew=fc;audit=au;encoder=pe;jwt=j;}
 /** Kept for focused legacy unit tests; production uses the injected constructor above. */
 public AuthService(UserRepository u,PersonRepository p,RoleRepository r,UserRoleRepository ur,EmailContactRepository e,PhoneContactRepository ph,AccountActivationRepository a,CommanderProfileRepository cp,AuditService au,PasswordEncoder pe,JwtService j){this(u,p,r,ur,e,ph,a,cp,null,null,au,pe,j);}
 @Transactional(readOnly=true) public TokenResponse login(LoginRequest request){ User u=users.findWithRolesByUsername(request.username()).orElseThrow(()->invalidCredentials()); if(!Boolean.TRUE.equals(u.getActivo())||!"ACTIVO".equals(u.getEstadoCuenta())||u.getPasswordHash()==null||!encoder.matches(request.password(),u.getPasswordHash()))throw invalidCredentials(); Set<String> rs=roleCodes(u); boolean mustChange=Boolean.TRUE.equals(u.getDebeCambiarContrasena()); return new TokenResponse(jwt.create(new CurrentUser(u.getId(),u.getUsername(),mustChange),rs,credentialVersion(u)),"Bearer",u.getUsername(),rs,mustChange); }
 @Transactional public ActivationCodeResponse createPending(CreatePendingUserRequest r, UUID actorId){
  if(r.correos()==null||r.correos().isEmpty())throw new ApiException(HttpStatus.BAD_REQUEST,"Debe informar al menos un correo"); if(r.telefonos()==null||r.telefonos().isEmpty())throw new ApiException(HttpStatus.BAD_REQUEST,"Debe informar al menos un teléfono"); String dni=canonicalDni(r.dni()); Optional<User> existing=Optional.ofNullable(users.findWithPersonByDni(dni)).orElse(Optional.empty()); if(existing.isPresent()){User found=existing.get();String code=Boolean.TRUE.equals(found.getActivo())?"USER_DNI_ALREADY_EXISTS":"INACTIVE_USER_WITH_DNI_EXISTS";String message=Boolean.TRUE.equals(found.getActivo())?"Ya existe un usuario activo con ese DNI":"Ya existe un usuario inactivo con ese DNI; puede reactivarlo";throw new ApiException(HttpStatus.CONFLICT,code,message,Map.of("userId",found.getId(),"username",Objects.toString(found.getUsername(),""),"nombre",found.getPerson().getNombre(),"apellido",found.getPerson().getApellido(),"dni",found.getPerson().getDni(),"activo",Boolean.TRUE.equals(found.getActivo())));} if(persons.existsByDni(dni)) throw new ApiException(HttpStatus.CONFLICT,"USER_DNI_ALREADY_EXISTS","Ya existe un usuario con ese DNI",Map.of());
  if(r.roles().contains("COMANDANTE")&&(r.licenciaAeronautica()==null||r.licenciaAeronautica().isBlank())) throw new ApiException(HttpStatus.BAD_REQUEST,"La licencia aeronáutica es obligatoria para COMANDANTE");
  Person p=new Person(); p.setNombre(r.nombre().trim());p.setApellido(r.apellido().trim());p.setDni(dni);p.setFechaNacimiento(r.fechaNacimiento()); persons.save(p);
  User u=new User();u.setPerson(p);u.setActivo(true);u.setEstadoCuenta("PENDIENTE_ACTIVACION");users.save(u); assignRoles(u,r.roles()); ensureCommanderProfile(p,r.roles(),r.licenciaAeronautica(),actorId); saveContacts(p,r.correos(),r.telefonos());
  return new ActivationCodeResponse(newActivation(u,actorId),"24 horas");
 }
 @Transactional public ActivationCodeResponse regenerate(UUID userId, UUID actorId){ User u=user(userId); if(!"PENDIENTE_ACTIVACION".equals(u.getEstadoCuenta()))throw new ApiException(HttpStatus.BAD_REQUEST,"La cuenta no está pendiente de activación"); activations.findOpenByUserId(userId).forEach(a->a.setUsedAt(LocalDateTime.now())); activations.flush(); return new ActivationCodeResponse(newActivation(u,actorId),"24 horas"); }
 @Transactional public void activate(ActivateAccountRequest r){
  if(!r.password().equals(r.confirmacionPassword()))throw new ApiException(HttpStatus.BAD_REQUEST,"Las contraseñas no coinciden");
  String dni=canonicalDni(r.dni()); List<AccountActivation> candidates=activations.findOpenByDni(dni);
  if(candidates.isEmpty()){
   User existing=users.findWithPersonByDni(dni).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"DNI inexistente"));
   if("ACTIVO".equals(existing.getEstadoCuenta()))throw new ApiException(HttpStatus.CONFLICT,"La cuenta ya está activada");
   throw new ApiException(HttpStatus.BAD_REQUEST,"No hay un código de activación vigente");
  }
  if(candidates.size()!=1)throw new ApiException(HttpStatus.BAD_REQUEST,"Código de activación inválido"); AccountActivation a=candidates.getFirst(); User u=a.getUser();
  if(!"PENDIENTE_ACTIVACION".equals(u.getEstadoCuenta())||!Boolean.TRUE.equals(u.getActivo()))throw new ApiException(HttpStatus.BAD_REQUEST,"La cuenta no está disponible para activación");
  if(a.getExpiresAt().isBefore(LocalDateTime.now()))throw new ApiException(HttpStatus.BAD_REQUEST,"El código de activación venció");
  if(!encoder.matches(r.codigo(),a.getTokenHash()))throw new ApiException(HttpStatus.BAD_REQUEST,"El código de activación es incorrecto");
  if(users.existsByUsername(r.username().trim()))throw new ApiException(HttpStatus.CONFLICT,"El nombre de usuario ya existe"); u.setUsername(r.username().trim());u.setPasswordHash(encoder.encode(r.password()));u.setEstadoCuenta("ACTIVO");u.setDebeCambiarContrasena(false);a.setUsedAt(LocalDateTime.now());
 }
 @Transactional(readOnly=true) public List<UserView> listUsers(){return users.findAllWithPersonAndRoles().stream().map(this::view).toList();}
 @Transactional(readOnly=true) public List<CommanderView> listActiveCommanders(){return users.findActiveByRoleCode("COMANDANTE").stream().filter(u->"ACTIVO".equals(u.getEstadoCuenta())&&u.getUsername()!=null&&u.getPerson().getCommanderProfile()!=null&&!u.getPerson().getCommanderProfile().getLicenseNumber().isBlank()).map(u->new CommanderView(u.getId(),u.getUsername(),u.getPerson().getNombre(),u.getPerson().getApellido(),u.getPerson().getCommanderProfile().getLicenseNumber(),u.getPerson().getCommanderProfile().getProvinciaActual()==null?null:u.getPerson().getCommanderProfile().getProvinciaActual().getNombre())).toList();}
 @Transactional(readOnly=true) public UserView myAccount(UUID id){return view(user(id));}
 @Transactional public UserView updateUser(UUID id,UpdateUserRequest r,UUID actorId){
  User u=user(id); Set<String> old=roleCodes(u); Set<String> next=new TreeSet<>(r.roles());
  if(id.equals(actorId)&&!old.equals(next))throw new ApiException(HttpStatus.FORBIDDEN,"No puede modificar sus propios roles");
  boolean removesLastActiveAdmin=Boolean.TRUE.equals(u.getActivo())&&old.contains("ADMINISTRADOR")&&(!r.activo()||!next.contains("ADMINISTRADOR"));
  if(removesLastActiveAdmin&&users.lockActiveAdministrators().size()<=1)throw new ApiException(HttpStatus.BAD_REQUEST,"No se puede desactivar o quitar el rol al último administrador activo.");
  Person p=u.getPerson();p.setNombre(r.nombre().trim());p.setApellido(r.apellido().trim());p.setFechaNacimiento(r.fechaNacimiento());ensureCommanderProfile(p,next,r.licenciaAeronautica(),actorId);
  boolean activeChanged=!Objects.equals(u.getActivo(),r.activo()); if(activeChanged)throw new ApiException(HttpStatus.CONFLICT,"USER_STATUS_CHANGE_REQUIRES_ACTION","Use las acciones específicas de desactivar o reactivar usuario",Map.of());
  userRoles.deleteAll(u.getUserRoles());u.getUserRoles().clear();assignRoles(u,next);
  if(!old.equals(next))audit(actorId,"USER_ROLE",u.getId(),"UPDATE",null,"{\"rolesChanged\":true}");
  if(old.contains("COMANDANTE")&&!next.contains("COMANDANTE"))audit(actorId,"USER_ROLE",u.getId(),"REMOVE_COMMANDER",null,"{\"role\":\"COMANDANTE\"}");
  if(!old.contains("COMANDANTE")&&next.contains("COMANDANTE"))audit(actorId,"USER_ROLE",u.getId(),"ASSIGN_COMMANDER",null,"{\"role\":\"COMANDANTE\"}");
  return view(u);
 }
 @Transactional public UserView deactivateUser(UUID id,UUID actorId,String motivo){
  if(id.equals(actorId))throw new ApiException(HttpStatus.BAD_REQUEST,"CANNOT_DEACTIVATE_SELF","No puede eliminar su propia cuenta.",Map.of()); User u=lockedUser(id); if(!Boolean.TRUE.equals(u.getActivo()))throw new ApiException(HttpStatus.CONFLICT,"USER_ALREADY_INACTIVE","El usuario ya está inactivo.",Map.of());if(u.getUsername()==null)throw new ApiException(HttpStatus.CONFLICT,"USER_PENDING_ACTIVATION","La cuenta aún no fue activada; gestione su código de activación en lugar de eliminarla.",Map.of());
  if(roleCodes(u).contains("ADMINISTRADOR")&&users.lockActiveAdministrators().size()<=1)throw new ApiException(HttpStatus.CONFLICT,"LAST_ACTIVE_ADMINISTRATOR","No se puede eliminar este usuario porque es el último administrador activo del sistema.",Map.of());
  Set<String> operationalStates=Set.of("APROBADO","PLANIFICADO","EN_CURSO"); if((flights!=null&&flights.existsOperationalCommanderAssignment(id,operationalStates))||(flightCrew!=null&&flightCrew.existsOperationalCrewAssignment(id,operationalStates)))throw new ApiException(HttpStatus.CONFLICT,"USER_HAS_OPERATIONAL_ASSIGNMENTS","El usuario tiene vuelos activos o planificados asignados. Reasigne sus responsabilidades antes de desactivarlo.",Map.of());
  u.setActivo(false);u.setEstadoCuenta("DESACTIVADO");u.setFechaBaja(LocalDateTime.now());u.invalidateCredentials();audit(actorId,"USER",u.getId(),"USUARIO_DESACTIVADO",null,"{\"motivo\":"+jsonString(blank(motivo))+"}");return view(u);
 }
 @Transactional public ReactivationResponse reactivateUser(UUID id,ReactivateUserRequest r,UUID actorId){
  User u=lockedUser(id);if(Boolean.TRUE.equals(u.getActivo()))throw new ApiException(HttpStatus.CONFLICT,"USER_ALREADY_ACTIVE","El usuario ya está activo.",Map.of());if(u.getUsername()==null)throw new ApiException(HttpStatus.CONFLICT,"USER_HAS_NO_USERNAME","La cuenta pendiente no puede reactivarse: regenere su código de activación.",Map.of()); Set<String> old=roleCodes(u),next=new TreeSet<>(r.roles()); Person p=u.getPerson();p.setNombre(r.nombre().trim());p.setApellido(r.apellido().trim());if(r.fechaNacimiento()!=null)p.setFechaNacimiento(r.fechaNacimiento());ensureCommanderProfile(p,next,r.licenciaAeronautica(),actorId);userRoles.deleteAll(u.getUserRoles());u.getUserRoles().clear();assignRoles(u,next);
  String password=newTemporaryPassword();u.setPasswordHash(encoder.encode(password));u.setDebeCambiarContrasena(true);u.setActivo(true);u.setEstadoCuenta("ACTIVO");u.setFechaBaja(null);u.invalidateCredentials();if(!old.equals(next))audit(actorId,"USER_ROLE",u.getId(),"UPDATE",null,"{\"rolesChanged\":true}");audit(actorId,"USER",u.getId(),"USUARIO_REACTIVADO",null,"{\"temporaryPasswordIssued\":true}");audit(actorId,"USER",u.getId(),"CONTRASENA_RESTABLECIDA",null,"{\"reason\":\"reactivacion\"}");return new ReactivationResponse(view(u),password);
 }
 @Transactional public void setTemporaryPassword(UUID id,TemporaryPasswordRequest r,UUID actorId){User u=lockedUser(id);if(!Boolean.TRUE.equals(u.getActivo())||u.getUsername()==null)throw new ApiException(HttpStatus.BAD_REQUEST,"La cuenta debe estar activa antes de asignar una contraseña temporal");u.setPasswordHash(encoder.encode(r.password()));u.setDebeCambiarContrasena(true);u.invalidateCredentials();audit(actorId,"USER",u.getId(),"CONTRASENA_RESTABLECIDA",null,"{\"reason\":\"administrative_reset\"}");}
 /** Compatibility entry point used internally by older callers; administrative HTTP calls use the locked variant. */
 @Transactional public void setTemporaryPassword(UUID id,TemporaryPasswordRequest r){User u=user(id);if(!Boolean.TRUE.equals(u.getActivo())||u.getUsername()==null)throw new ApiException(HttpStatus.BAD_REQUEST,"La cuenta debe estar activa antes de asignar una contraseña temporal");u.setPasswordHash(encoder.encode(r.password()));u.setDebeCambiarContrasena(true);u.invalidateCredentials();}
 @Transactional public void changePassword(UUID id,ChangePasswordRequest r){User u=user(id);if(!r.nuevaPassword().equals(r.confirmacionPassword()))throw new ApiException(HttpStatus.BAD_REQUEST,"Las contraseñas no coinciden");if(u.getPasswordHash()==null||!encoder.matches(r.passwordActual(),u.getPasswordHash()))throw new ApiException(HttpStatus.BAD_REQUEST,"La contraseña actual no es válida");u.setPasswordHash(encoder.encode(r.nuevaPassword()));u.setDebeCambiarContrasena(false);u.invalidateCredentials();}
 @Transactional public ContactView addEmail(UUID userId,ContactRequest r){User u=user(userId);EmailContact e=new EmailContact();e.setPerson(u.getPerson());e.setDireccion(r.direccion().trim());e.setTipo(defaultType(r.tipo()));e.setPrincipal(emails.countByPersonId(u.getPerson().getId())==0);emails.save(e);return emailView(e);}
 @Transactional public ContactView addPhone(UUID userId,PhoneRequest r){User u=user(userId);PhoneContact p=new PhoneContact();p.setPerson(u.getPerson());p.setNumero(r.numero().trim());p.setTipo(defaultType(r.tipo()));p.setPrincipal(phones.countByPersonId(u.getPerson().getId())==0);phones.save(p);return phoneView(p);}
 @Transactional public void deleteEmail(UUID userId,UUID contactId){EmailContact e=emails.findById(contactId).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Correo inexistente"));if(!e.getPerson().getId().equals(user(userId).getPerson().getId()))throw forbidden();if(emails.countByPersonId(e.getPerson().getId())<=1)throw new ApiException(HttpStatus.BAD_REQUEST,"No se puede eliminar el último correo");emails.delete(e);}
 @Transactional public void deletePhone(UUID userId,UUID contactId){PhoneContact p=phones.findById(contactId).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Teléfono inexistente"));if(!p.getPerson().getId().equals(user(userId).getPerson().getId()))throw forbidden();if(phones.countByPersonId(p.getPerson().getId())<=1)throw new ApiException(HttpStatus.BAD_REQUEST,"No se puede eliminar el último teléfono");phones.delete(p);}
 @Transactional public void makePrimaryEmail(UUID userId,UUID id){User u=user(userId);EmailContact target=emails.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Correo inexistente"));if(!target.getPerson().getId().equals(u.getPerson().getId()))throw forbidden();emails.findByPersonIdOrderByPrincipalDesc(u.getPerson().getId()).forEach(x->x.setPrincipal(x.getId().equals(id)));}
 @Transactional public void makePrimaryPhone(UUID userId,UUID id){User u=user(userId);PhoneContact target=phones.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Teléfono inexistente"));if(!target.getPerson().getId().equals(u.getPerson().getId()))throw forbidden();phones.findByPersonIdOrderByPrincipalDesc(u.getPerson().getId()).forEach(x->x.setPrincipal(x.getId().equals(id)));}
 @Transactional public void createBootstrapAdmin(String username,String password,String email){ if(users.findAllWithPersonAndRoles().stream().anyMatch(u->roleCodes(u).contains("ADMINISTRADOR")))return; Person p=new Person();p.setNombre("Administrador");p.setApellido("Inicial");persons.save(p);User u=new User();u.setPerson(p);u.setUsername(username);u.setPasswordHash(encoder.encode(password));u.setEstadoCuenta("ACTIVO");users.save(u);assignRoles(u,Set.of("ADMINISTRADOR"));EmailContact e=new EmailContact();e.setPerson(p);e.setDireccion(email);e.setPrincipal(true);emails.save(e); }
 private String newActivation(User u,UUID actorId){byte[] bytes=new byte[24];random.nextBytes(bytes);String code=Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);AccountActivation a=new AccountActivation();a.setUser(u);a.setTokenHash(encoder.encode(code));a.setCreatedAt(LocalDateTime.now());a.setExpiresAt(a.getCreatedAt().plusHours(24));if(actorId!=null)a.setCreatedBy(user(actorId));activations.save(a);return code;}
 private void saveContacts(Person p,List<ContactRequest> es,List<PhoneRequest> ps){for(int i=0;i<es.size();i++){EmailContact e=new EmailContact();e.setPerson(p);e.setDireccion(es.get(i).direccion().trim());e.setTipo(defaultType(es.get(i).tipo()));e.setPrincipal(i==0);emails.save(e);}for(int i=0;i<ps.size();i++){PhoneContact ph=new PhoneContact();ph.setPerson(p);ph.setNumero(ps.get(i).numero().trim());ph.setTipo(defaultType(ps.get(i).tipo()));ph.setPrincipal(i==0);phones.save(ph);}}
 private void assignRoles(User u,Set<String> codes){for(String code:codes){Role role=roles.findByCodigo(code).orElseThrow(()->new ApiException(HttpStatus.BAD_REQUEST,"Rol inexistente: "+code));userRoles.save(new UserRole(u,role));}}
 private void ensureCommanderProfile(Person p,Set<String> roles,String license,UUID actorId){if(!roles.contains("COMANDANTE"))return; String value=canonicalLicense(license); CommanderProfile profile=p.getCommanderProfile(); if(profile==null){if(value==null)throw new ApiException(HttpStatus.BAD_REQUEST,"La licencia aeronáutica es obligatoria para COMANDANTE");if(commanderProfiles.existsByLicenseNumberIgnoreCase(value))throw new ApiException(HttpStatus.CONFLICT,"La licencia aeronáutica ya existe");profile=new CommanderProfile();profile.setPerson(p);profile.setLicenseNumber(value);commanderProfiles.save(profile);p.setCommanderProfile(profile);audit(actorId,"COMMANDER_PROFILE",p.getId(),"CREATE",null,"{\"profileCreated\":true}");}else if(value!=null&&!value.equals(profile.getLicenseNumber())){if(commanderProfiles.existsByLicenseNumberIgnoreCase(value))throw new ApiException(HttpStatus.CONFLICT,"La licencia aeronáutica ya existe");profile.setLicenseNumber(value);audit(actorId,"COMMANDER_PROFILE",p.getId(),"UPDATE_LICENSE", "{\"licenseChanged\":true}","{\"licenseChanged\":true}");}}
 private void audit(UUID actorId,String type,UUID entityId,String operation,String before,String after){audit.record(null,actorId==null?null:users.findById(actorId).orElse(null),type,entityId,operation,before,after);}
 private User user(UUID id){return users.findWithPersonById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Usuario inexistente"));}
 private User lockedUser(UUID id){return users.lockWithPersonAndRolesById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Usuario inexistente"));}
 private long credentialVersion(User u){return u.getVersionCredenciales()==null?1L:u.getVersionCredenciales();}
 private String newTemporaryPassword(){byte[] bytes=new byte[18];random.nextBytes(bytes);return Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);}
 private String jsonString(String value){return value==null?"null":"\""+value.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n").replace("\r","\\r")+"\"";}
 private Set<String> roleCodes(User u){Set<String> result=new TreeSet<>();for(UserRole r:u.getUserRoles())if(Boolean.TRUE.equals(r.getRole().getActivo()))result.add(r.getRole().getCodigo());return result;}
 private UserView view(User u){Person p=u.getPerson();List<ContactView> es=emails.findByPersonIdOrderByPrincipalDesc(p.getId()).stream().map(this::emailView).toList();List<ContactView> ps=phones.findByPersonIdOrderByPrincipalDesc(p.getId()).stream().map(this::phoneView).toList();CommanderProfile cp=p.getCommanderProfile();return new UserView(u.getId(),p.getNombre(),p.getApellido(),p.getDni(),u.getUsername(),u.getEstadoCuenta(),Boolean.TRUE.equals(u.getActivo()),u.getFechaBaja(),roleCodes(u),es,ps,cp==null||cp.getProvinciaActual()==null?null:cp.getProvinciaActual().getNombre());}
 private ContactView emailView(EmailContact e){return new ContactView(e.getId(),e.getDireccion(),e.getTipo(),Boolean.TRUE.equals(e.getPrincipal()));} private ContactView phoneView(PhoneContact p){return new ContactView(p.getId(),p.getNumero(),p.getTipo(),Boolean.TRUE.equals(p.getPrincipal()));}
 private String blank(String v){return v==null||v.isBlank()?null:v.trim();} private String canonicalLicense(String v){String value=blank(v);if(value==null)return null;value=value.toUpperCase(Locale.ROOT);if(!value.matches("[A-Z0-9]+"))throw new ApiException(HttpStatus.BAD_REQUEST,"La licencia debe ser alfanumérica");return value;} private String canonicalDni(String v){String value=v==null?"":v.replaceAll("\\D","");if(value.isBlank())throw new ApiException(HttpStatus.BAD_REQUEST,"El DNI debe contener dígitos");return value;}private String defaultType(String v){return v==null||v.isBlank()?"PERSONAL":v.trim();} private ApiException invalidCredentials(){return new ApiException(HttpStatus.UNAUTHORIZED,"Credenciales inválidas");}private ApiException forbidden(){return new ApiException(HttpStatus.FORBIDDEN,"Acceso denegado");}
}
