package com.vuelossanitarios.backend.service;
import com.vuelossanitarios.backend.api.ApiException;
import com.vuelossanitarios.backend.api.dto.AuthDtos.*;
import com.vuelossanitarios.backend.domain.person.*;
import com.vuelossanitarios.backend.domain.user.*;
import com.vuelossanitarios.backend.repository.*;
import com.vuelossanitarios.backend.security.*;
import org.springframework.http.HttpStatus;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.security.SecureRandom;
import java.time.*;
import java.util.*;

@Service public class AuthService {
 private static final Set<String> OPERATIONAL=Set.of("DTS","OPERACIONES","CENTRO_OPERACIONES","COMANDANTE");
 private final UserRepository users; private final PersonRepository persons; private final RoleRepository roles; private final UserRoleRepository userRoles; private final EmailContactRepository emails; private final PhoneContactRepository phones; private final AccountActivationRepository activations; private final PasswordEncoder encoder; private final JwtService jwt; private final SecureRandom random=new SecureRandom();
 public AuthService(UserRepository u,PersonRepository p,RoleRepository r,UserRoleRepository ur,EmailContactRepository e,PhoneContactRepository ph,AccountActivationRepository a,PasswordEncoder pe,JwtService j){users=u;persons=p;roles=r;userRoles=ur;emails=e;phones=ph;activations=a;encoder=pe;jwt=j;}
 @Transactional(readOnly=true) public TokenResponse login(LoginRequest request){ User u=users.findWithRolesByUsername(request.username()).orElseThrow(()->invalidCredentials()); if(!Boolean.TRUE.equals(u.getActivo())||!"ACTIVO".equals(u.getEstadoCuenta())||u.getPasswordHash()==null||!encoder.matches(request.password(),u.getPasswordHash()))throw invalidCredentials(); Set<String> rs=roleCodes(u); boolean mustChange=Boolean.TRUE.equals(u.getDebeCambiarContrasena()); return new TokenResponse(jwt.create(new CurrentUser(u.getId(),u.getUsername(),mustChange),rs),"Bearer",u.getUsername(),rs,mustChange); }
 @Transactional public ActivationCodeResponse createPending(CreatePendingUserRequest r, UUID actorId){
  if(persons.existsByDni(r.dni().trim())) throw new ApiException(HttpStatus.CONFLICT,"El DNI ya existe"); validateRoles(r.roles());
  if(r.roles().contains("COMANDANTE")&&(r.licenciaAeronautica()==null||r.licenciaAeronautica().isBlank())) throw new ApiException(HttpStatus.BAD_REQUEST,"La licencia aeronáutica es obligatoria para COMANDANTE");
  Person p=new Person(); p.setNombre(r.nombre().trim());p.setApellido(r.apellido().trim());p.setDni(r.dni().trim());p.setFechaNacimiento(r.fechaNacimiento()); persons.save(p);
  User u=new User();u.setPerson(p);u.setLicenciaAeronautica(blank(r.licenciaAeronautica()));u.setActivo(true);u.setEstadoCuenta("PENDIENTE_ACTIVACION");users.save(u); assignRoles(u,r.roles()); saveContacts(p,r.correos(),r.telefonos());
  return new ActivationCodeResponse(newActivation(u,actorId),"24 horas");
 }
 @Transactional public ActivationCodeResponse regenerate(UUID userId, UUID actorId){ User u=user(userId); if(!"PENDIENTE_ACTIVACION".equals(u.getEstadoCuenta()))throw new ApiException(HttpStatus.BAD_REQUEST,"La cuenta no está pendiente de activación"); activations.findOpenByUserId(userId).forEach(a->a.setUsedAt(LocalDateTime.now())); return new ActivationCodeResponse(newActivation(u,actorId),"24 horas"); }
 @Transactional public void activate(ActivateAccountRequest r){
  if(!r.password().equals(r.confirmacionPassword()))throw new ApiException(HttpStatus.BAD_REQUEST,"Las contraseñas no coinciden");
  List<AccountActivation> candidates=activations.findOpenByDni(r.dni().trim()); if(candidates.size()!=1)throw new ApiException(HttpStatus.BAD_REQUEST,"Código de activación inválido"); AccountActivation a=candidates.getFirst(); User u=a.getUser();
  if(!"PENDIENTE_ACTIVACION".equals(u.getEstadoCuenta())||!Boolean.TRUE.equals(u.getActivo())||a.getExpiresAt().isBefore(LocalDateTime.now())||!encoder.matches(r.codigo(),a.getTokenHash()))throw new ApiException(HttpStatus.BAD_REQUEST,"Código de activación inválido o vencido");
  if(users.existsByUsername(r.username().trim()))throw new ApiException(HttpStatus.CONFLICT,"El nombre de usuario ya existe"); u.setUsername(r.username().trim());u.setPasswordHash(encoder.encode(r.password()));u.setEstadoCuenta("ACTIVO");u.setDebeCambiarContrasena(false);a.setUsedAt(LocalDateTime.now());
 }
 @Transactional(readOnly=true) public List<UserView> listUsers(){return users.findAllWithPersonAndRoles().stream().map(this::view).toList();}
 @Transactional(readOnly=true) public UserView myAccount(UUID id){return view(user(id));}
 @Transactional public UserView updateUser(UUID id,UpdateUserRequest r){User u=user(id); validateRoles(r.roles()); if(r.roles().contains("COMANDANTE")&&(r.licenciaAeronautica()==null||r.licenciaAeronautica().isBlank()))throw new ApiException(HttpStatus.BAD_REQUEST,"La licencia aeronáutica es obligatoria para COMANDANTE"); Person p=u.getPerson();p.setNombre(r.nombre().trim());p.setApellido(r.apellido().trim());p.setFechaNacimiento(r.fechaNacimiento());u.setLicenciaAeronautica(blank(r.licenciaAeronautica())); u.setActivo(r.activo()); if(!r.activo())u.setEstadoCuenta("DESACTIVADO"); else if("DESACTIVADO".equals(u.getEstadoCuenta()))u.setEstadoCuenta(u.getUsername()==null?"PENDIENTE_ACTIVACION":"ACTIVO"); userRoles.deleteAll(u.getUserRoles());u.getUserRoles().clear();assignRoles(u,r.roles()); return view(u); }
 @Transactional public void setTemporaryPassword(UUID id,TemporaryPasswordRequest r){User u=user(id);if(u.getUsername()==null)throw new ApiException(HttpStatus.BAD_REQUEST,"La cuenta debe activarse antes de asignar una contraseña temporal");u.setPasswordHash(encoder.encode(r.password()));u.setDebeCambiarContrasena(true);}
 @Transactional public void changePassword(UUID id,ChangePasswordRequest r){User u=user(id);if(!r.nuevaPassword().equals(r.confirmacionPassword()))throw new ApiException(HttpStatus.BAD_REQUEST,"Las contraseñas no coinciden");if(u.getPasswordHash()==null||!encoder.matches(r.passwordActual(),u.getPasswordHash()))throw new ApiException(HttpStatus.BAD_REQUEST,"La contraseña actual no es válida");u.setPasswordHash(encoder.encode(r.nuevaPassword()));u.setDebeCambiarContrasena(false);}
 @Transactional public ContactView addEmail(UUID userId,ContactRequest r){User u=user(userId);EmailContact e=new EmailContact();e.setPerson(u.getPerson());e.setDireccion(r.direccion().trim());e.setTipo(defaultType(r.tipo()));e.setPrincipal(emails.countByPersonId(u.getPerson().getId())==0);emails.save(e);return emailView(e);}
 @Transactional public ContactView addPhone(UUID userId,PhoneRequest r){User u=user(userId);PhoneContact p=new PhoneContact();p.setPerson(u.getPerson());p.setNumero(r.numero().trim());p.setTipo(defaultType(r.tipo()));p.setPrincipal(phones.countByPersonId(u.getPerson().getId())==0);phones.save(p);return phoneView(p);}
 @Transactional public void deleteEmail(UUID userId,UUID contactId){EmailContact e=emails.findById(contactId).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Correo inexistente"));if(!e.getPerson().getId().equals(user(userId).getPerson().getId()))throw forbidden();if(emails.countByPersonId(e.getPerson().getId())<=1)throw new ApiException(HttpStatus.BAD_REQUEST,"No se puede eliminar el último correo");emails.delete(e);}
 @Transactional public void deletePhone(UUID userId,UUID contactId){PhoneContact p=phones.findById(contactId).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Teléfono inexistente"));if(!p.getPerson().getId().equals(user(userId).getPerson().getId()))throw forbidden();if(phones.countByPersonId(p.getPerson().getId())<=1)throw new ApiException(HttpStatus.BAD_REQUEST,"No se puede eliminar el último teléfono");phones.delete(p);}
 @Transactional public void makePrimaryEmail(UUID userId,UUID id){User u=user(userId);EmailContact target=emails.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Correo inexistente"));if(!target.getPerson().getId().equals(u.getPerson().getId()))throw forbidden();emails.findByPersonIdOrderByPrincipalDesc(u.getPerson().getId()).forEach(x->x.setPrincipal(x.getId().equals(id)));}
 @Transactional public void makePrimaryPhone(UUID userId,UUID id){User u=user(userId);PhoneContact target=phones.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Teléfono inexistente"));if(!target.getPerson().getId().equals(u.getPerson().getId()))throw forbidden();phones.findByPersonIdOrderByPrincipalDesc(u.getPerson().getId()).forEach(x->x.setPrincipal(x.getId().equals(id)));}
 @Transactional public void createBootstrapAdmin(String username,String password,String email){ if(users.findAllWithPersonAndRoles().stream().anyMatch(u->roleCodes(u).contains("ADMINISTRADOR")))return; Person p=new Person();p.setNombre("Administrador");p.setApellido("Inicial");persons.save(p);User u=new User();u.setPerson(p);u.setUsername(username);u.setPasswordHash(encoder.encode(password));u.setEstadoCuenta("ACTIVO");users.save(u);assignRoles(u,Set.of("ADMINISTRADOR"));EmailContact e=new EmailContact();e.setPerson(p);e.setDireccion(email);e.setPrincipal(true);emails.save(e); }
 private String newActivation(User u,UUID actorId){byte[] bytes=new byte[24];random.nextBytes(bytes);String code=Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);AccountActivation a=new AccountActivation();a.setUser(u);a.setTokenHash(encoder.encode(code));a.setCreatedAt(LocalDateTime.now());a.setExpiresAt(a.getCreatedAt().plusHours(24));if(actorId!=null)a.setCreatedBy(user(actorId));activations.save(a);return code;}
 private void saveContacts(Person p,List<ContactRequest> es,List<PhoneRequest> ps){for(int i=0;i<es.size();i++){EmailContact e=new EmailContact();e.setPerson(p);e.setDireccion(es.get(i).direccion().trim());e.setTipo(defaultType(es.get(i).tipo()));e.setPrincipal(i==0);emails.save(e);}for(int i=0;i<ps.size();i++){PhoneContact ph=new PhoneContact();ph.setPerson(p);ph.setNumero(ps.get(i).numero().trim());ph.setTipo(defaultType(ps.get(i).tipo()));ph.setPrincipal(i==0);phones.save(ph);}}
 private void assignRoles(User u,Set<String> codes){for(String code:codes){Role role=roles.findByCodigo(code).orElseThrow(()->new ApiException(HttpStatus.BAD_REQUEST,"Rol inexistente: "+code));userRoles.save(new UserRole(u,role));}}
 private void validateRoles(Set<String> codes){if(codes.contains("ADMINISTRADOR")&&codes.stream().anyMatch(OPERATIONAL::contains))throw new ApiException(HttpStatus.BAD_REQUEST,"ADMINISTRADOR no puede combinarse con roles operativos");}
 private User user(UUID id){return users.findWithPersonById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Usuario inexistente"));}
 private Set<String> roleCodes(User u){Set<String> result=new TreeSet<>();for(UserRole r:u.getUserRoles())if(Boolean.TRUE.equals(r.getRole().getActivo()))result.add(r.getRole().getCodigo());return result;}
 private UserView view(User u){Person p=u.getPerson();List<ContactView> es=emails.findByPersonIdOrderByPrincipalDesc(p.getId()).stream().map(this::emailView).toList();List<ContactView> ps=phones.findByPersonIdOrderByPrincipalDesc(p.getId()).stream().map(this::phoneView).toList();return new UserView(u.getId(),p.getNombre(),p.getApellido(),p.getDni(),u.getUsername(),u.getEstadoCuenta(),Boolean.TRUE.equals(u.getActivo()),roleCodes(u),es,ps);}
 private ContactView emailView(EmailContact e){return new ContactView(e.getId(),e.getDireccion(),e.getTipo(),Boolean.TRUE.equals(e.getPrincipal()));} private ContactView phoneView(PhoneContact p){return new ContactView(p.getId(),p.getNumero(),p.getTipo(),Boolean.TRUE.equals(p.getPrincipal()));}
 private String blank(String v){return v==null||v.isBlank()?null:v.trim();}private String defaultType(String v){return v==null||v.isBlank()?"PERSONAL":v.trim();} private ApiException invalidCredentials(){return new ApiException(HttpStatus.UNAUTHORIZED,"Credenciales inválidas");}private ApiException forbidden(){return new ApiException(HttpStatus.FORBIDDEN,"Acceso denegado");}
}
