package com.vuelossanitarios.backend.service;
import com.vuelossanitarios.backend.api.*;
import com.vuelossanitarios.backend.api.dto.DocumentDtos.*;
import com.vuelossanitarios.backend.domain.catalog.DocumentType;
import com.vuelossanitarios.backend.domain.flight.*;
import com.vuelossanitarios.backend.domain.user.User;
import com.vuelossanitarios.backend.repository.*;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;
import java.util.*;
@Service public class DocumentService {
 private final FlightRepository flights;private final DocumentTypeRepository types;private final DocumentItemRepository items;private final FlightDocumentRepository versions;private final UserRepository users;private final DocumentStorage storage;private final AuditService audit;private final FlightAuthorizationService access;
 public DocumentService(FlightRepository f,DocumentTypeRepository t,DocumentItemRepository i,FlightDocumentRepository v,UserRepository u,DocumentStorage s,AuditService a,FlightAuthorizationService ac){flights=f;types=t;items=i;versions=v;users=u;storage=s;audit=a;access=ac;}
 @Transactional public DocumentView createPdf(UUID flightId,String type,String title,MultipartFile file,UUID actor){Flight f=flights.lockById(flightId).orElseThrow(()->notFound("Vuelo"));mayChange(f,actor);String key=storage.storePdf(file);try{FlightDocumentItem item=newItem(f,type,title,DocumentModality.PDF);items.save(item);FlightDocument v=pdfVersion(item,file,key,user(actor));versions.save(v);audit.record(f,user(actor),"DOCUMENT",v.getId(),"CREATE",null,"{\"version\":1}");return view(item,v);}catch(RuntimeException e){storage.deleteQuietly(key);throw e;}}
 @Transactional public DocumentView replacePdf(UUID itemId,MultipartFile file,UUID actor){FlightDocumentItem item=items.lockById(itemId).orElseThrow(()->notFound("Documento"));mayChange(item.getFlight(),actor);if(item.getModalidad()!=DocumentModality.PDF)throw bad("El documento no es PDF");String key=storage.storePdf(file);try{FlightDocument v=pdfVersion(item,file,key,user(actor));advance(item,v);audit.record(item.getFlight(),user(actor),"DOCUMENT",v.getId(),"CREATE_VERSION",null,"{\"version\":"+v.getVersion()+"}");return view(item,v);}catch(RuntimeException e){storage.deleteQuietly(key);throw e;}}
 @Transactional public DocumentView createText(UUID flightId,CreateText request,UUID actor){Flight f=flights.lockById(flightId).orElseThrow(()->notFound("Vuelo"));mayChange(f,actor);FlightDocumentItem item=newItem(f,request.documentTypeCode(),request.titulo(),DocumentModality.TEXT);items.save(item);FlightDocument v=textVersion(item,request.contenido(),user(actor));versions.save(v);audit.record(f,user(actor),"TEXT",v.getId(),"CREATE",null,"{\"version\":1}");return view(item,v);}
 @Transactional public DocumentView replaceText(UUID itemId,ReplaceText request,UUID actor){FlightDocumentItem item=items.lockById(itemId).orElseThrow(()->notFound("Documento"));mayChange(item.getFlight(),actor);if(item.getModalidad()!=DocumentModality.TEXT)throw bad("El documento no es texto");FlightDocument v=textVersion(item,request.contenido(),user(actor));advance(item,v);audit.record(item.getFlight(),user(actor),"TEXT",v.getId(),"CREATE_VERSION",null,"{\"version\":"+v.getVersion()+"}");return view(item,v);}
 @Transactional(readOnly=true) public List<DocumentView> history(UUID itemId,UUID actor){FlightDocumentItem item=items.findById(itemId).orElseThrow(()->notFound("Documento"));access.mayRead(item.getFlight(),actor);return versions.findByDocumentItemIdOrderByVersionDesc(itemId).stream().map(v->view(item,v)).toList();}
 @Transactional(readOnly=true) public Download download(UUID versionId,UUID actor){FlightDocument v=versions.findById(versionId).orElseThrow(()->notFound("Versión"));access.mayRead(v.getDocumentItem().getFlight(),actor);if(v.getStorageKey()==null)throw bad("La versión es texto");return new Download(v.getNombreArchivo(),storage.read(v.getStorageKey()).bytes());}
 private FlightDocumentItem newItem(Flight f,String code,String title,DocumentModality mode){DocumentType t=types.findByCodigo(code).orElseThrow(()->bad("Tipo documental inexistente"));FlightDocumentItem i=new FlightDocumentItem();i.setFlight(f);i.setDocumentType(t);i.setTitulo(title);i.setModalidad(mode);return i;}
 private FlightDocument pdfVersion(FlightDocumentItem item,MultipartFile file,String key,User actor){FlightDocument v=base(item,actor);v.setNombreArchivo(safeName(file.getOriginalFilename()));v.setStorageKey(key);v.setMimeType("application/pdf");v.setTamanioBytes(file.getSize());return v;}private FlightDocument textVersion(FlightDocumentItem item,String text,User actor){FlightDocument v=base(item,actor);v.setContenidoTexto(text);return v;}private FlightDocument base(FlightDocumentItem item,User actor){FlightDocument v=new FlightDocument();v.setDocumentItem(item);Integer max=versions.maxVersion(item.getId());v.setVersion(max==null?1:max+1);v.setEsVersionActual(true);v.setCreadoPor(actor);return v;}private void advance(FlightDocumentItem item,FlightDocument v){versions.findByDocumentItemIdAndEsVersionActualTrue(item.getId()).ifPresent(old->old.setEsVersionActual(false));versions.save(v);}private void mayChange(Flight f,UUID actor){access.mayRead(f,actor);if("FINALIZADO".equals(f.getStatus().getCodigo()))throw bad("El vuelo finalizado no admite documentos");}private User user(UUID id){return users.findById(id).orElseThrow(()->notFound("Usuario"));}private String safeName(String n){if(n==null)return"documento.pdf";String v=n.replaceAll("[^a-zA-Z0-9._-]","_");return v.isBlank()?"documento.pdf":v.substring(0,Math.min(255,v.length()));}private DocumentView view(FlightDocumentItem i,FlightDocument v){return new DocumentView(i.getId().toString(),v.getVersion(),v.getEsVersionActual(),i.getModalidad().name(),i.getTitulo());}private ApiException bad(String s){return new ApiException(HttpStatus.BAD_REQUEST,s);}private ApiException notFound(String s){return new ApiException(HttpStatus.NOT_FOUND,s+" inexistente");}public record Download(String filename,byte[] data){}
}
