package com.vuelossanitarios.backend.service;
import com.vuelossanitarios.backend.api.ApiException;
import com.vuelossanitarios.backend.api.dto.FinalReportDtos.*;
import com.vuelossanitarios.backend.domain.catalog.FlightStatus;
import com.vuelossanitarios.backend.domain.flight.*;
import com.vuelossanitarios.backend.domain.user.User;
import com.vuelossanitarios.backend.repository.*;
import java.time.*;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service public class FinalReportWorkflowService {
 private final FinalReportObligationRepository obligations; private final FlightFinalReportRepository reports; private final FlightRepository flights; private final FlightStatusRepository statuses; private final UserRepository users; private final NotificationService notifications; private final AuditService audit; private final CommanderReportAccessService access; private final Clock clock;
 public FinalReportWorkflowService(FinalReportObligationRepository o,FlightFinalReportRepository r,FlightRepository f,FlightStatusRepository s,UserRepository u,NotificationService n,AuditService a,CommanderReportAccessService ac,Clock c){obligations=o;reports=r;flights=f;statuses=s;users=u;notifications=n;audit=a;access=ac;clock=c;}
 @Transactional public void createObligationAfterFinish(Flight flight,User actor){if(flight.getComandante()==null)throw bad("El vuelo finalizado debe tener comandante asignado");if(obligations.findByFlightIdAndCurrentTrue(flight.getId()).isPresent())return;OffsetDateTime due=now().plusHours(48);FinalReportObligation o=new FinalReportObligation();o.setFlight(flight);o.setCommander(flight.getComandante());o.setObligationNumber(1);o.setStatus(FinalReportStatus.PENDIENTE);o.setOriginalDueAt(due);o.setDueAt(due);obligations.save(o);audit.record(flight,actor,"FINAL_REPORT_OBLIGATION",o.getId(),"CREATE",null,"{\"dueAt\":\""+due+"\"}");notifications.create(o.getCommander(),flight,"FINAL_REPORT_PENDING","El vuelo "+flight.getCodigo()+" finalizó. Debe presentar el informe final antes de "+due);}
 @Transactional public ObligationView submit(UUID obligationId,Submit req,UUID actorId){FinalReportObligation o=locked(obligationId);requireCommander(o,actorId);if(!"FINALIZADO".equals(o.getFlight().getStatus().getCodigo()))throw bad("El informe sólo puede presentarse con el vuelo finalizado");if(o.getStatus()==FinalReportStatus.APROBADO)throw bad("El informe aprobado no admite versiones nuevas");if(req.texto()==null||req.texto().trim().isEmpty())throw bad("Debe ingresar texto del informe o adjuntar una modalidad válida");reports.findByFlightIdAndEsVersionActualTrue(o.getFlight().getId()).ifPresent(x->x.setEsVersionActual(false));FlightFinalReport r=new FlightFinalReport();r.setFlight(o.getFlight());r.setVersion(reports.countByFlightId(o.getFlight().getId())+1);r.setEsVersionActual(true);r.setHorasVuelo(req.horasVuelo());r.setCombustibleConsumidoLitros(req.combustibleConsumidoLitros());r.setIncidentes(req.incidentes());r.setResumen(req.texto().trim());r.setCreadoPor(user(actorId));reports.save(r);o.setReport(r);o.setStatus(FinalReportStatus.PRESENTADO);o.setPresentedAt(now());audit.record(o.getFlight(),user(actorId),"FINAL_REPORT",r.getId(),"SUBMIT",null,"{\"version\":"+r.getVersion()+"}");for(User op:users.findActiveByRoleCode("OPERACIONES"))notifications.create(op,o.getFlight(),"FINAL_REPORT_SUBMITTED","Informe final presentado para el vuelo "+o.getFlight().getCodigo());return view(o);}
 @Transactional public ObligationView extend(UUID obligationId,UUID actorId){FinalReportObligation o=locked(obligationId);requireCommander(o,actorId);if(o.getExtensionUsed())throw bad("La prórroga ya fue utilizada para esta obligación");if(o.getStatus()!=FinalReportStatus.PENDIENTE&&o.getStatus()!=FinalReportStatus.DEVUELTO)throw bad("La prórroga sólo está disponible para un informe pendiente de presentación");OffsetDateTime before=o.getDueAt(),now=now();o.setDueAt(now.isAfter(before)?now.plusHours(24):before.plusHours(24));o.setExtensionUsed(true);o.setExtendedAt(now);audit.record(o.getFlight(),user(actorId),"FINAL_REPORT_OBLIGATION",o.getId(),"EXTEND","{\"dueAt\":\""+before+"\"}","{\"dueAt\":\""+o.getDueAt()+"\"}");notifications.create(o.getCommander(),o.getFlight(),"FINAL_REPORT_EXTENSION","Prórroga concedida hasta "+o.getDueAt()+" para el vuelo "+o.getFlight().getCodigo());return view(o);}
 @Transactional public ObligationView review(UUID obligationId,Review req,UUID actorId){FinalReportObligation o=locked(obligationId);if(o.getStatus()!=FinalReportStatus.PRESENTADO||o.getReport()==null||!Boolean.TRUE.equals(o.getReport().getEsVersionActual()))throw bad("Sólo se puede revisar la versión actual presentada");User op=user(actorId);if(Boolean.TRUE.equals(req.aprobar())){o.setStatus(FinalReportStatus.APROBADO);o.setApprovedAt(now());o.setApprovedBy(op);o.getFlight().setStatus(status("COMPLETADO"));audit.record(o.getFlight(),op,"FINAL_REPORT",o.getReport().getId(),"APPROVE",null,"{\"status\":\"COMPLETADO\"}");notifications.create(o.getCommander(),o.getFlight(),"FINAL_REPORT_APPROVED","Informe final aprobado; el vuelo "+o.getFlight().getCodigo()+" fue completado.");}else{if(req.motivoDevolucion()==null||req.motivoDevolucion().trim().isEmpty())throw bad("La devolución requiere un motivo");OffsetDateTime due=now().plusHours(48);o.setStatus(FinalReportStatus.DEVUELTO);o.setReturnReason(req.motivoDevolucion().trim());o.setReturnedAt(now());o.setReturnedBy(op);o.setOriginalDueAt(due);o.setDueAt(due);o.setExtensionUsed(false);o.setExtendedAt(null);audit.record(o.getFlight(),op,"FINAL_REPORT",o.getReport().getId(),"RETURN",null,"{\"dueAt\":\""+due+"\"}");notifications.create(o.getCommander(),o.getFlight(),"FINAL_REPORT_RETURNED","Informe devuelto para corrección: "+o.getReturnReason());}return view(o);}
 @Transactional(readOnly=true) public List<ObligationView> mine(UUID commander){return obligations.findByCommanderIdAndCurrentTrueOrderByDueAtAsc(commander).stream().map(this::view).toList();}
 @Transactional(readOnly=true) public List<ObligationView> pendingReview(){return obligations.findByStatusAndCurrentTrueOrderByPresentedAtAsc(FinalReportStatus.PRESENTADO).stream().map(this::view).toList();}
 private FinalReportObligation locked(UUID id){return obligations.lockById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Obligación de informe inexistente"));}private void requireCommander(FinalReportObligation o,UUID id){if(!o.getCommander().getId().equals(id))throw new ApiException(HttpStatus.FORBIDDEN,"Sólo el comandante responsable puede presentar este informe");}private User user(UUID id){return users.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Usuario inexistente"));}private FlightStatus status(String code){return statuses.findByCodigo(code).orElseThrow(()->new IllegalStateException("Catálogo de estados incompleto"));}private OffsetDateTime now(){return OffsetDateTime.ofInstant(Instant.now(clock),ZoneOffset.UTC);}private ApiException bad(String s){return new ApiException(HttpStatus.BAD_REQUEST,s);}private ObligationView view(FinalReportObligation o){return new ObligationView(o.getId(),o.getFlight().getId(),o.getFlight().getCodigo(),o.getStatus().name(),o.getDueAt(),o.getOriginalDueAt(),Boolean.TRUE.equals(o.getExtensionUsed()),o.getPresentedAt(),o.getReturnReason(),access.isBlocked(o.getCommander().getId()));}
}
