package com.vuelossanitarios.backend.service;
import com.vuelossanitarios.backend.api.ApiException;
import com.vuelossanitarios.backend.api.dto.FlightDtos.*;
import com.vuelossanitarios.backend.domain.catalog.*;
import com.vuelossanitarios.backend.domain.flight.*;
import com.vuelossanitarios.backend.domain.patient.Patient;
import com.vuelossanitarios.backend.domain.user.User;
import com.vuelossanitarios.backend.repository.*;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.*;
import java.time.LocalDateTime;
import java.util.*;
@Service public class FlightService {
 private final FlightRepository flights; private final PatientRepository patients; private final UserRepository users; private final FlightStatusRepository statuses; private final FlightPriorityRepository priorities; private final AircraftRepository aircraft; private final AirportRepository airports; private final CrewRoleRepository crewRoles; private final FlightCrewRepository crews; private final FlightMedicalInfoRepository medical; private final FlightFinalReportRepository reports; private final AuditService audit; private final FlightAuthorizationService access; private final NotificationService notifications; private final FlightUrgencyPolicy urgencyPolicy; private final FinalReportWorkflowService reportWorkflow; private final CommanderReportAccessService commanderAccess;
 public FlightService(FlightRepository f,PatientRepository p,UserRepository u,FlightStatusRepository s,FlightPriorityRepository pr,AircraftRepository a,AirportRepository ap,CrewRoleRepository cr,FlightCrewRepository c,FlightMedicalInfoRepository m,FlightFinalReportRepository r,AuditService au,FlightAuthorizationService ac,NotificationService ns,FlightUrgencyPolicy up,FinalReportWorkflowService rw,CommanderReportAccessService ca){flights=f;patients=p;users=u;statuses=s;priorities=pr;aircraft=a;airports=ap;crewRoles=cr;crews=c;medical=m;reports=r;audit=au;access=ac;notifications=ns;urgencyPolicy=up;reportWorkflow=rw;commanderAccess=ca;}
 @Transactional public FlightView create(CreateFlight req, UUID actorId){
  urgencyPolicy.validate(req.fechaSolicitada(),req.extremaUrgencia(),req.justificacionExtremaUrgencia(),req.fechaLimiteTraslado());
  User actor=user(actorId); Patient patient=patients.findById(req.patientId()).orElseThrow(()->notFound("Paciente")); Flight f=new Flight();f.setCodigo("VS-"+UUID.randomUUID().toString().substring(0,8).toUpperCase());f.setPatient(patient);f.setSolicitadoPor(actor);f.setFechaSolicitada(req.fechaSolicitada());f.setExtremaUrgencia(req.extremaUrgencia());f.setJustificacionExtremaUrgencia(req.extremaUrgencia()?req.justificacionExtremaUrgencia().trim():null);f.setFechaLimiteTraslado(req.extremaUrgencia()?req.fechaLimiteTraslado():null);f.setMotivoSolicitud(req.motivoSolicitud());f.setCiudadOrigenSolicitada(req.ciudadOrigenSolicitada());f.setCiudadDestinoSolicitada(req.ciudadDestinoSolicitada());f.setPriority(priority(req.priorityCode()));f.setStatus(status("SOLICITADO"));flights.save(f); FlightMedicalInfo m=new FlightMedicalInfo();m.setFlight(f);m.setDiagnostico(req.medical().diagnostico());m.setCondicionMedica(req.medical().condicionMedica());m.setRequiereEquipamientoEspecial(req.medical().requiereEquipamientoEspecial());m.setObservaciones(req.medical().observaciones());medical.save(m);
  String urgencyAudit="{\"extremaUrgencia\":"+f.getExtremaUrgencia()+",\"justificacion\":"+json(f.getJustificacionExtremaUrgencia())+",\"fechaLimiteTraslado\":"+json(f.getFechaLimiteTraslado()==null?null:f.getFechaLimiteTraslado().toString())+"}";
  audit.record(f,actor,"FLIGHT",f.getId(),"CREATE",null,"{\"status\":\"SOLICITADO\",\"urgencia\":"+urgencyAudit+"}");
  if(Boolean.TRUE.equals(f.getExtremaUrgencia())) for(User operations : users.findActiveByRoleCode("OPERACIONES")) notifications.create(operations,f,"EXTREME_URGENCY_REQUEST","EXTREMA URGENCIA: solicitud "+f.getCodigo()+" requerida para "+f.getFechaSolicitada()+"; límite "+f.getFechaLimiteTraslado());
  return view(f); }
 @Transactional public FlightView evaluate(UUID id,Evaluation req,UUID actorId){Flight f=locked(id);requireStatus(f,"SOLICITADO");User a=user(actorId);f.setEvaluadoPor(a);f.setFechaEvaluacion(LocalDateTime.now());if(req.priorityCode()!=null&&!req.priorityCode().isBlank())f.setPriority(priority(req.priorityCode()));if(Boolean.TRUE.equals(req.aprobar())){f.setStatus(status("APROBADO"));f.setMotivoRechazo(null);}else {if(req.motivoRechazo()==null||req.motivoRechazo().isBlank())throw bad("El rechazo requiere motivo");f.setStatus(status("RECHAZADO"));f.setMotivoRechazo(req.motivoRechazo());}audit.record(f,a,"FLIGHT",f.getId(),"EVALUATE",null,"{\"status\":\""+f.getStatus().getCodigo()+"\"}");notifications.create(f.getSolicitadoPor(),f,"FLIGHT_"+f.getStatus().getCodigo(),"La solicitud "+f.getCodigo()+" fue "+f.getStatus().getNombre().toLowerCase());return view(f);}
 @Transactional(isolation=Isolation.SERIALIZABLE) public FlightView assign(UUID id,AssignResources req,UUID actorId){Flight f=locked(id);requireStatus(f,"APROBADO");f.setAircraft(aircraft.findById(req.aircraftId()).orElseThrow(()->notFound("Aeronave")));User commander=user(req.comandanteId());if(!hasRole(commander,"COMANDANTE"))throw bad("El usuario no posee rol COMANDANTE");commanderAccess.requireOperationalAccess(commander.getId());f.setComandante(commander);audit.record(f,user(actorId),"FLIGHT",f.getId(),"ASSIGN_RESOURCES",null,"{\"assigned\":true}");String type=Boolean.TRUE.equals(f.getExtremaUrgencia())?"EXTREME_URGENCY_COMMANDER_ASSIGNED":"COMMANDER_ASSIGNED";String message=Boolean.TRUE.equals(f.getExtremaUrgencia())?"EXTREMA URGENCIA: fue asignado al vuelo "+f.getCodigo()+"; límite "+f.getFechaLimiteTraslado():"Fue asignado al vuelo "+f.getCodigo();notifications.create(commander,f,type,message);return view(f);}
 @Transactional(isolation=Isolation.SERIALIZABLE) public FlightView plan(UUID id,Plan req,UUID actorId){Flight f=locked(id);requireStatus(f,"APROBADO");requireCommander(f,actorId);commanderAccess.requireOperationalAccess(actorId);if(f.getAircraft()==null||f.getComandante()==null)throw bad("Se requiere aeronave y comandante");if(!req.llegada().isAfter(req.salida()))throw bad("La llegada debe ser posterior a la salida");f.setOrigen(airports.findById(req.origenId()).orElseThrow(()->notFound("Aeropuerto origen")));f.setDestino(airports.findById(req.destinoId()).orElseThrow(()->notFound("Aeropuerto destino")));if(req.origenId().equals(req.destinoId()))throw bad("Origen y destino deben ser distintos");f.setFechaPlanificadaSalida(req.salida());f.setFechaPlanificadaLlegada(req.llegada());assertNoOverlap(f);f.setStatus(status("PLANIFICADO"));audit.record(f,user(actorId),"FLIGHT",f.getId(),"PLAN",null,"{\"status\":\"PLANIFICADO\"}");return view(f);}
 @Transactional public FlightView start(UUID id,UUID actorId){Flight f=locked(id);requireStatus(f,"PLANIFICADO");requireOperations(actorId);f.setFechaSalidaReal(LocalDateTime.now());f.setStatus(status("EN_CURSO"));audit.record(f,user(actorId),"FLIGHT",f.getId(),"START",null,"{\"status\":\"EN_CURSO\"}");return view(f);}
 @Transactional public FlightView finish(UUID id,UUID actorId){Flight f=locked(id);requireStatus(f,"EN_CURSO");requireOperations(actorId);f.setFechaLlegadaReal(LocalDateTime.now());f.setStatus(status("FINALIZADO"));reportWorkflow.createObligationAfterFinish(f,user(actorId));audit.record(f,user(actorId),"FLIGHT",f.getId(),"FINISH",null,"{\"status\":\"FINALIZADO\"}");return view(f);}
 @Transactional public FlightView cancel(UUID id,Cancel req,UUID actorId){Flight f=locked(id);access.mayRead(f,actorId);String s=f.getStatus().getCodigo();if(s.equals("EN_CURSO")||s.equals("FINALIZADO")||s.equals("COMPLETADO")||s.equals("CANCELADO"))throw bad("El vuelo no puede cancelarse en su estado actual");f.setMotivoCancelacion(req.motivo());f.setFechaCancelacion(LocalDateTime.now());f.setCanceladoPor(user(actorId));f.setStatus(status("CANCELADO"));audit.record(f,user(actorId),"FLIGHT",f.getId(),"CANCEL",null,"{\"status\":\"CANCELADO\"}");return view(f);}
 @Transactional public void addCrew(UUID id,Crew req,UUID actorId){Flight f=locked(id);ensureMutable(f);requireCommander(f,actorId);commanderAccess.requireOperationalAccess(actorId);User member=user(req.userId());if(crews.existsByFlightIdAndUserId(id,member.getId()))throw new ApiException(HttpStatus.CONFLICT,"El usuario ya integra la tripulación");CrewRole role=crewRoles.findByCodigo(req.crewRoleCode()).orElseThrow(()->bad("Rol de tripulación inexistente"));if("COMANDANTE".equals(role.getCodigo())&&!member.getId().equals(f.getComandante()==null?null:f.getComandante().getId()))throw bad("El comandante de tripulación debe coincidir con el responsable");FlightCrew c=new FlightCrew();c.setFlight(f);c.setUser(member);c.setCrewRole(role);c.setAsignadoPor(user(actorId));crews.save(c);audit.record(f,user(actorId),"FLIGHT_CREW",c.getId(),"CREATE",null,"{\"role\":\""+role.getCodigo()+"\"}");}
 @Transactional public void saveFinalReport(UUID id,FinalReport req,UUID actorId){Flight f=locked(id);if(!"EN_CURSO".equals(f.getStatus().getCodigo()))throw bad("El informe se carga durante la ejecución");requireCommander(f,actorId);reports.findByFlightIdAndEsVersionActualTrue(id).ifPresent(r->r.setEsVersionActual(false));FlightFinalReport report=new FlightFinalReport();report.setFlight(f);report.setVersion(reports.countByFlightId(id)+1);report.setEsVersionActual(true);report.setHorasVuelo(req.horasVuelo());report.setCombustibleConsumidoLitros(req.combustibleConsumidoLitros());report.setIncidentes(req.incidentes());report.setResumen(req.resumen());report.setCreadoPor(user(actorId));reports.save(report);audit.record(f,user(actorId),"FINAL_REPORT",report.getId(),"CREATE_VERSION",null,"{\"version\":"+report.getVersion()+"}");}
 @Transactional(readOnly=true) public FlightView get(UUID id,UUID actor){Flight f=flights.findById(id).orElseThrow(()->notFound("Vuelo"));access.mayRead(f,actor);return view(f);}
 @Transactional(readOnly=true) public List<FlightView> list(UUID actor){User u=users.findWithRolesByUsername(user(actor).getUsername()).orElseThrow();boolean broad=hasOperationsRole(u);List<Flight> result=broad?flights.findAll():hasRole(u,"COMANDANTE")?flights.findByComandanteId(actor):flights.findBySolicitadoPorId(actor);return result.stream().sorted((a,b)->{boolean ap="SOLICITADO".equals(a.getStatus().getCodigo()),bp="SOLICITADO".equals(b.getStatus().getCodigo());if(ap&&bp){int urgency=Boolean.compare(Boolean.TRUE.equals(b.getExtremaUrgencia()),Boolean.TRUE.equals(a.getExtremaUrgencia()));if(urgency!=0)return urgency;if(Boolean.TRUE.equals(a.getExtremaUrgencia()))return a.getFechaLimiteTraslado().compareTo(b.getFechaLimiteTraslado());}return a.getFechaSolicitada().compareTo(b.getFechaSolicitada());}).map(this::view).toList();}
 private void assertNoOverlap(Flight f){boolean conflict=flights.overlappingAircraft(f.getAircraft().getId(),f.getFechaPlanificadaSalida(),f.getFechaPlanificadaLlegada()).stream().anyMatch(x->!x.getId().equals(f.getId()))||flights.overlappingCommander(f.getComandante().getId(),f.getFechaPlanificadaSalida(),f.getFechaPlanificadaLlegada()).stream().anyMatch(x->!x.getId().equals(f.getId()));if(conflict)throw new ApiException(HttpStatus.CONFLICT,"Existe una asignación con horario incompatible");}
 private void ensureMutable(Flight f){if("FINALIZADO".equals(f.getStatus().getCodigo())||"COMPLETADO".equals(f.getStatus().getCodigo()))throw bad("El vuelo cerrado no admite modificaciones");}
 private void requireCommander(Flight f,UUID id){if(f.getComandante()==null||!f.getComandante().getId().equals(id))throw new ApiException(HttpStatus.FORBIDDEN,"Sólo el comandante asignado puede realizar esta operación");}
 private void requireStatus(Flight f,String s){if(!s.equals(f.getStatus().getCodigo()))throw bad("Transición no permitida desde "+f.getStatus().getCodigo());} private void requireOperations(UUID id){if(!hasOperationsRole(user(id)))throw new ApiException(HttpStatus.FORBIDDEN,"Sólo Centro de Operaciones puede ejecutar esta transición");} private User user(UUID id){return users.findById(id).orElseThrow(()->notFound("Usuario"));}private Flight locked(UUID id){return flights.lockById(id).orElseThrow(()->notFound("Vuelo"));}private FlightStatus status(String c){return statuses.findByCodigo(c).orElseThrow(()->new IllegalStateException("Catálogo de estados incompleto"));}private FlightPriority priority(String c){return priorities.findByCodigoAndActivoTrue(c).orElseThrow(()->bad("Prioridad inexistente o inactiva"));}private boolean hasRole(User u,String code){return users.findWithRolesByUsername(u.getUsername()).orElseThrow().getUserRoles().stream().anyMatch(x->code.equals(x.getRole().getCodigo()));}private boolean hasOperationsRole(User u){return hasRole(u,"OPERACIONES")||hasRole(u,"CENTRO_OPERACIONES");}private ApiException bad(String m){return new ApiException(HttpStatus.BAD_REQUEST,m);}private ApiException notFound(String m){return new ApiException(HttpStatus.NOT_FOUND,m+" inexistente");}private String json(String value){return value==null?"null":"\""+value.replace("\\","\\\\").replace("\"","\\\"")+"\"";}private FlightView view(Flight f){return new FlightView(f.getId(),f.getCodigo(),f.getStatus().getCodigo(),f.getPatient().getId(),f.getPriority()==null?null:f.getPriority().getCodigo(),f.getCiudadOrigenSolicitada(),f.getCiudadDestinoSolicitada(),f.getFechaSolicitada(),Boolean.TRUE.equals(f.getExtremaUrgencia()),f.getJustificacionExtremaUrgencia(),f.getFechaLimiteTraslado(),f.getFechaPlanificadaSalida(),f.getFechaPlanificadaLlegada());}
}
