package com.vuelossanitarios.backend.service;

import com.vuelossanitarios.backend.api.ApiException;
import com.vuelossanitarios.backend.api.dto.FlightDtos.*;
import com.vuelossanitarios.backend.domain.catalog.*;
import com.vuelossanitarios.backend.domain.flight.*;
import com.vuelossanitarios.backend.domain.patient.Patient;
import com.vuelossanitarios.backend.domain.person.CommanderProfile;
import com.vuelossanitarios.backend.domain.user.User;
import com.vuelossanitarios.backend.repository.*;
import java.time.LocalDateTime;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.*;

/** Transactional state machine for request scheduling, resources and execution. */
@Service public class FlightService {
 private final FlightRepository flights; private final PatientRepository patients; private final UserRepository users; private final FlightStatusRepository statuses; private final FlightPriorityRepository priorities; private final AircraftRepository aircraft; private final AirportRepository airports; private final LocalityRepository localities; private final CrewRoleRepository crewRoles; private final FlightCrewRepository crews; private final FlightMedicalInfoRepository medical; private final FlightFinalReportRepository reports; private final FlightScheduleNegotiationRepository negotiations; private final AuditService audit; private final FlightAuthorizationService access; private final NotificationService notifications; private final FlightUrgencyPolicy urgencyPolicy; private final FinalReportWorkflowService reportWorkflow; private final CommanderReportAccessService commanderAccess;
 public FlightService(FlightRepository f,PatientRepository p,UserRepository u,FlightStatusRepository s,FlightPriorityRepository pr,AircraftRepository a,AirportRepository ap,LocalityRepository l,CrewRoleRepository cr,FlightCrewRepository c,FlightMedicalInfoRepository m,FlightFinalReportRepository r,FlightScheduleNegotiationRepository n,AuditService au,FlightAuthorizationService ac,NotificationService ns,FlightUrgencyPolicy up,FinalReportWorkflowService rw,CommanderReportAccessService ca){flights=f;patients=p;users=u;statuses=s;priorities=pr;aircraft=a;airports=ap;localities=l;crewRoles=cr;crews=c;medical=m;reports=r;negotiations=n;audit=au;access=ac;notifications=ns;urgencyPolicy=up;reportWorkflow=rw;commanderAccess=ca;}

 @Transactional public FlightView create(CreateFlight req,UUID actorId){
  urgencyPolicy.validate(req.fechaSolicitada(),req.extremaUrgencia(),req.justificacionExtremaUrgencia(),req.fechaLimiteTraslado()); User actor=user(actorId); Patient patient=patients.findById(req.patientId()).orElseThrow(()->notFound("Paciente")); Locality origin=locality(req.localidadOrigenId(),"origen"),destination=locality(req.localidadDestinoId(),"destino"); if(origin.getId().equals(destination.getId()))throw bad("La localidad de origen y destino deben ser distintas.");
  Flight f=new Flight(); f.setCodigo("VS-"+UUID.randomUUID().toString().substring(0,8).toUpperCase()); f.setPatient(patient); f.setSolicitadoPor(actor); f.setFechaSolicitada(req.fechaSolicitada()); f.setExtremaUrgencia(req.extremaUrgencia()); f.setJustificacionExtremaUrgencia(req.extremaUrgencia()?req.justificacionExtremaUrgencia().trim():null); f.setFechaLimiteTraslado(req.extremaUrgencia()?req.fechaLimiteTraslado():null); f.setMotivoSolicitud(req.motivoSolicitud()); f.setLocalidadOrigenSolicitada(origin); f.setLocalidadDestinoSolicitada(destination); f.setPriority(priority(req.priorityCode())); f.setStatus(status("SOLICITADO")); flights.save(f);
  FlightMedicalInfo m=new FlightMedicalInfo();m.setFlight(f);m.setDiagnostico(req.medical().diagnostico());m.setCondicionMedica(req.medical().condicionMedica());m.setRequiereEquipamientoEspecial(req.medical().requiereEquipamientoEspecial());m.setObservaciones(req.medical().observaciones());medical.save(m);
  negotiation(f,"DTS_PROPUESTA",f.getFechaSolicitada(),null,actor); audit.record(f,actor,"FLIGHT",f.getId(),"DTS_SCHEDULE_PROPOSAL",null,"{\"fechaHora\":"+json(f.getFechaSolicitada().toString())+"}");
  if(Boolean.TRUE.equals(f.getExtremaUrgencia())) for(User op:users.findActiveByRoleCode("OPERACIONES"))notifications.create(op,f,"EXTREME_URGENCY_REQUEST","EXTREMA URGENCIA: solicitud "+f.getCodigo()+" propuesta para "+f.getFechaSolicitada()+"; límite "+f.getFechaLimiteTraslado());
  return view(f);
 }

 /** Backward-compatible endpoint: approval accepts DTS's hour, rejection cancels. */
 @Transactional public FlightView evaluate(UUID id,Evaluation req,UUID actorId){ if(Boolean.TRUE.equals(req.aprobar()))return acceptRequestedSchedule(id,actorId); return rejectDirectly(id,new Cancel(requiredReason(req.motivoRechazo(),"El rechazo requiere motivo")),actorId); }
 @Transactional public FlightView acceptRequestedSchedule(UUID id,UUID actorId){ Flight f=locked(id);requireOperations(actorId);requireStatus(f,"SOLICITADO");User actor=user(actorId);fixSchedule(f,f.getFechaSolicitada(),"CO_ACEPTA_PROPUESTA",null,actor);notifications.create(f.getSolicitadoPor(),f,"SCHEDULE_ACCEPTED","Centro de Operaciones aceptó el horario propuesto para "+f.getCodigo());return view(f); }
 @Transactional public FlightView counterproposal(UUID id,CounterProposal req,UUID actorId){ Flight f=locked(id);requireOperations(actorId);requireStatus(f,"SOLICITADO");User actor=user(actorId);String reason=requiredReason(req.motivo(),"La contrapropuesta requiere motivo");validateCounterproposal(f,req.salida());f.setEvaluadoPor(actor);f.setFechaEvaluacion(LocalDateTime.now());f.setStatus(status("PENDIENTE_RESPUESTA_DTS"));negotiation(f,"CO_CONTRAPROPUESTA",req.salida(),reason,actor);audit.record(f,actor,"FLIGHT",f.getId(),"CO_COUNTERPROPOSAL",null,"{\"fechaHora\":"+json(req.salida().toString())+",\"motivo\":"+json(reason)+"}");notifications.create(f.getSolicitadoPor(),f,"SCHEDULE_COUNTERPROPOSAL","Centro de Operaciones propuso "+req.salida()+" para "+f.getCodigo()+": "+reason);return view(f); }
 @Transactional public FlightView respondToCounterproposal(UUID id,NegotiationResponse req,UUID actorId){ Flight f=locked(id);requireStatus(f,"PENDIENTE_RESPUESTA_DTS");User actor=user(actorId);if(!f.getSolicitadoPor().getId().equals(actorId))throw new ApiException(HttpStatus.FORBIDDEN,"Sólo DTS solicitante puede responder la contrapropuesta");FlightScheduleNegotiation proposed=lastCounterproposal(f);if(Boolean.TRUE.equals(req.aceptar())){fixSchedule(f,proposed.getFechaHoraPropuesta(),"DTS_ACEPTA_CONTRAPROPUESTA",null,actor);notifications.create(f.getEvaluadoPor(),f,"SCHEDULE_COUNTERPROPOSAL_ACCEPTED","DTS aceptó la contrapropuesta de "+f.getCodigo());}else{String reason=requiredReason(req.motivoRechazo(),"El rechazo de la contrapropuesta requiere motivo");cancelNegotiation(f,actor,"DTS_RECHAZA_CONTRAPROPUESTA",reason);notifications.create(f.getEvaluadoPor(),f,"SCHEDULE_COUNTERPROPOSAL_REJECTED","DTS rechazó la contrapropuesta de "+f.getCodigo()+": "+reason);}return view(f); }
 @Transactional public FlightView rejectDirectly(UUID id,Cancel req,UUID actorId){ Flight f=locked(id);requireOperations(actorId);requireStatus(f,"SOLICITADO");cancelNegotiation(f,user(actorId),"CO_RECHAZO_DIRECTO",requiredReason(req.motivo(),"El rechazo requiere motivo"));notifications.create(f.getSolicitadoPor(),f,"SCHEDULE_REJECTED","Centro de Operaciones rechazó la solicitud "+f.getCodigo()+": "+f.getMotivoCancelacion());return view(f); }

 /** Deprecated CO planning is intentionally rejected: the commander owns route and arrival. */
 @Transactional public FlightView configurePlanning(UUID id,Plan req,UUID actorId){requireOperations(actorId);throw bad("La planificación operativa corresponde al comandante asignado. Operaciones sólo fija el horario y asigna recursos.");}
 @Transactional public FlightView configureOperationalPlanning(UUID id,OperationalPlan req,UUID actorId){Flight f=locked(id);requireStatus(f,"PLANIFICADO");requireCommander(f,actorId);commanderAccess.requireOperationalAccess(actorId);if(f.getFechaPlanificadaSalida()==null)throw bad("No existe una salida planificada definitiva");if(!req.llegada().isAfter(f.getFechaPlanificadaSalida()))throw bad("La llegada debe ser posterior a la salida definitiva");Airport origin=activeAirport(req.origenId(),"origen"),destination=activeAirport(req.destinoId(),"destino");if(origin.getId().equals(destination.getId()))throw bad("Origen y destino deben ser distintos");if(!provinceId(origin).equals(originProvince(f)))throw bad("El aeropuerto de origen debe pertenecer a la provincia de origen solicitada");if(!provinceId(destination).equals(destinationProvince(f)))throw bad("El aeropuerto de destino debe pertenecer a la provincia de destino solicitada");f.setOrigen(origin);f.setDestino(destination);f.setFechaPlanificadaLlegada(req.llegada());assertNoOverlap(f);audit.record(f,user(actorId),"FLIGHT",f.getId(),"COMMANDER_OPERATIONAL_PLANNING",null,"{\"origenId\":"+json(origin.getId().toString())+",\"destinoId\":"+json(destination.getId().toString())+",\"llegada\":"+json(req.llegada().toString())+"}");return view(f);}

 @Transactional(readOnly=true) public List<AvailableAircraftView> availableAircraft(UUID id,UUID actorId){Flight f=flights.findById(id).orElseThrow(()->notFound("Vuelo"));requireOperations(actorId);requireStatus(f,"APROBADO");UUID province=originProvince(f);return aircraft.findActiveLocatedInProvince(province).stream().filter(a->flights.activeAircraftAssignments(a.getId(),List.of("EN_CURSO")).isEmpty()).map(this::aircraftView).toList();}
 @Transactional(readOnly=true) public List<AvailableCommanderView> availableCommanders(UUID id,UUID actorId){Flight f=flights.findById(id).orElseThrow(()->notFound("Vuelo"));requireOperations(actorId);requireStatus(f,"APROBADO");return users.findAvailableCommandersInProvince(originProvince(f)).stream().filter(u->{try{commanderAccess.requireOperationalAccess(u.getId());return true;}catch(ApiException e){return false;}}).map(this::commanderView).toList();}
 @Transactional(isolation=Isolation.SERIALIZABLE) public FlightView assign(UUID id,AssignResources req,UUID actorId){Flight f=locked(id);requireOperations(actorId);requireStatus(f,"APROBADO");if(f.getFechaPlanificadaSalida()==null)throw bad("Primero debe fijarse la fecha y hora definitiva");User actor=user(actorId);Aircraft plane=aircraft.lockById(req.aircraftId()).orElseThrow(()->notFound("Aeronave"));if(!Boolean.TRUE.equals(plane.getActivo())||plane.getAeropuertoActual()==null)throw bad("La aeronave no está activa o no tiene ubicación operativa");if(!provinceId(plane.getAeropuertoActual()).equals(originProvince(f)))throw bad("La aeronave debe estar en un aeropuerto de la provincia de origen");if(!flights.activeAircraftAssignments(plane.getId(),List.of("EN_CURSO")).isEmpty())throw new ApiException(HttpStatus.CONFLICT,"La aeronave seleccionada se encuentra en vuelo");User commander=user(req.comandanteId());CommanderProfile profile=commander.getPerson().getCommanderProfile();if(!hasRole(commander,"COMANDANTE")||profile==null||profile.getLicenseNumber().isBlank()||profile.getProvinciaActual()==null)throw bad("El comandante debe tener licencia y provincia actual configuradas");if(!profile.getProvinciaActual().getId().equals(originProvince(f)))throw bad("El comandante debe encontrarse en la provincia de origen");commanderAccess.requireOperationalAccess(commander.getId());f.setAircraft(plane);f.setComandante(commander);f.setStatus(status("PLANIFICADO"));if(!crews.existsByFlightIdAndUserId(id,commander.getId())){CrewRole role=crewRoles.findByCodigo("COMANDANTE").orElseThrow(()->new IllegalStateException("Rol COMANDANTE inexistente"));FlightCrew crew=new FlightCrew();crew.setFlight(f);crew.setUser(commander);crew.setCrewRole(role);crew.setAsignadoPor(actor);crews.save(crew);}audit.record(f,actor,"FLIGHT",f.getId(),"ASSIGN_COMMANDER",null,"{\"comandanteId\":"+json(commander.getId().toString())+"}");audit.record(f,actor,"FLIGHT",f.getId(),"ASSIGN_AIRCRAFT",null,"{\"aeronaveId\":"+json(plane.getId().toString())+"}");notifications.create(commander,f,Boolean.TRUE.equals(f.getExtremaUrgencia())?"EXTREME_URGENCY_COMMANDER_ASSIGNED":"COMMANDER_ASSIGNED","Fue asignado al vuelo "+f.getCodigo()+". Complete la planificación operativa.");return view(f);}
 @Transactional public FlightView start(UUID id,UUID actorId){Flight f=locked(id);requireStatus(f,"PLANIFICADO");requireOperations(actorId);if(f.getAircraft()==null||f.getOrigen()==null||f.getDestino()==null||f.getFechaPlanificadaLlegada()==null)throw bad("El comandante debe completar la planificación operativa antes de iniciar el vuelo");f.setFechaSalidaReal(LocalDateTime.now());f.setStatus(status("EN_CURSO"));audit.record(f,user(actorId),"FLIGHT",f.getId(),"START",null,"{\"status\":\"EN_CURSO\"}");return view(f);}
 @Transactional public FlightView finish(UUID id,UUID actorId){Flight f=locked(id);requireStatus(f,"EN_CURSO");requireOperations(actorId);if(f.getAircraft()==null||f.getDestino()==null||f.getComandante()==null)throw bad("El vuelo no posee datos operativos suficientes para finalizar");User actor=user(actorId);Aircraft plane=aircraft.lockById(f.getAircraft().getId()).orElseThrow(()->notFound("Aeronave"));Airport before=plane.getAeropuertoActual();plane.setAeropuertoActual(f.getDestino());CommanderProfile profile=f.getComandante().getPerson().getCommanderProfile();if(profile==null)throw bad("El comandante no posee perfil operativo");Province beforeProvince=profile.getProvinciaActual();profile.setProvinciaActual(f.getDestino().getProvinciaReferencial());f.setFechaLlegadaReal(LocalDateTime.now());f.setStatus(status("FINALIZADO"));reportWorkflow.createObligationAfterFinish(f,actor);audit.record(f,actor,"AIRCRAFT",plane.getId(),"UPDATE_LOCATION_AFTER_FINISH",before==null?null:"{\"aeropuertoActualId\":"+json(before.getId().toString())+"}","{\"aeropuertoActualId\":"+json(f.getDestino().getId().toString())+"}");audit.record(f,actor,"COMMANDER_PROFILE",profile.getPerson().getId(),"UPDATE_LOCATION_AFTER_FINISH",beforeProvince==null?null:"{\"provinciaActualId\":"+json(beforeProvince.getId().toString())+"}","{\"provinciaActualId\":"+json(f.getDestino().getProvinciaReferencial().getId().toString())+"}");audit.record(f,actor,"FLIGHT",f.getId(),"FINISH",null,"{\"status\":\"FINALIZADO\"}");return view(f);}
 @Transactional public FlightView cancel(UUID id,Cancel req,UUID actorId){Flight f=locked(id);access.mayRead(f,actorId);String s=f.getStatus().getCodigo();if(Set.of("EN_CURSO","FINALIZADO","COMPLETADO","CANCELADO").contains(s))throw bad("El vuelo no puede cancelarse en su estado actual");User actor=user(actorId);f.setMotivoCancelacion(requiredReason(req.motivo(),"La cancelación requiere motivo"));f.setFechaCancelacion(LocalDateTime.now());f.setCanceladoPor(actor);f.setStatus(status("CANCELADO"));audit.record(f,actor,"FLIGHT",f.getId(),"CANCEL",null,"{\"status\":\"CANCELADO\"}");return view(f);}
 @Transactional public void addCrew(UUID id,Crew req,UUID actorId){Flight f=locked(id);ensureMutable(f);requireCommander(f,actorId);commanderAccess.requireOperationalAccess(actorId);User member=user(req.userId());if(crews.existsByFlightIdAndUserId(id,member.getId()))throw new ApiException(HttpStatus.CONFLICT,"El usuario ya integra la tripulación");CrewRole role=crewRoles.findByCodigo(req.crewRoleCode()).orElseThrow(()->bad("Rol de tripulación inexistente"));if("COMANDANTE".equals(role.getCodigo())&&!member.getId().equals(f.getComandante()==null?null:f.getComandante().getId()))throw bad("El comandante de tripulación debe coincidir con el responsable");FlightCrew c=new FlightCrew();c.setFlight(f);c.setUser(member);c.setCrewRole(role);c.setAsignadoPor(user(actorId));crews.save(c);audit.record(f,user(actorId),"FLIGHT_CREW",c.getId(),"CREATE",null,"{\"role\":"+json(role.getCodigo())+"}");}
 @Transactional public void saveFinalReport(UUID id,FinalReport req,UUID actorId){Flight f=locked(id);if(!"EN_CURSO".equals(f.getStatus().getCodigo()))throw bad("El informe se carga durante la ejecución");requireCommander(f,actorId);reports.findByFlightIdAndEsVersionActualTrue(id).ifPresent(r->r.setEsVersionActual(false));FlightFinalReport report=new FlightFinalReport();report.setFlight(f);report.setVersion(reports.countByFlightId(id)+1);report.setEsVersionActual(true);report.setHorasVuelo(req.horasVuelo());report.setCombustibleConsumidoLitros(req.combustibleConsumidoLitros());report.setIncidentes(req.incidentes());report.setResumen(req.resumen());report.setCreadoPor(user(actorId));reports.save(report);audit.record(f,user(actorId),"FINAL_REPORT",report.getId(),"CREATE_VERSION",null,"{\"version\":"+report.getVersion()+"}");}
 @Transactional(readOnly=true) public FlightDetailView get(UUID id,UUID actor){Flight f=flights.findById(id).orElseThrow(()->notFound("Vuelo"));access.mayRead(f,actor);return detail(f);}
 @Transactional(readOnly=true) public List<FlightView> list(UUID actor){User u=users.findWithRolesByUsername(user(actor).getUsername()).orElseThrow();boolean broad=hasOperationsRole(u);List<Flight> result=broad?flights.findAll():hasRole(u,"COMANDANTE")?flights.findByComandanteId(actor):flights.findBySolicitadoPorId(actor);return result.stream().sorted(Comparator.comparing(Flight::getFechaSolicitada)).map(this::view).toList();}

 private void fixSchedule(Flight f,LocalDateTime departure,String event,String reason,User actor){validateCounterproposal(f,departure);f.setEvaluadoPor(actor);f.setFechaEvaluacion(LocalDateTime.now());f.setFechaPlanificadaSalida(departure);f.setStatus(status("APROBADO"));negotiation(f,event,departure,reason,actor);audit.record(f,actor,"FLIGHT",f.getId(),event,null,"{\"fechaHoraSalidaPlanificada\":"+json(departure.toString())+"}");}
 private void cancelNegotiation(Flight f,User actor,String event,String reason){f.setEvaluadoPor(actor);f.setFechaEvaluacion(LocalDateTime.now());f.setMotivoCancelacion(reason);f.setFechaCancelacion(LocalDateTime.now());f.setCanceladoPor(actor);f.setStatus(status("CANCELADO"));negotiation(f,event,null,reason,actor);audit.record(f,actor,"FLIGHT",f.getId(),event,null,"{\"motivo\":"+json(reason)+",\"status\":\"CANCELADO\"}");}
 private void validateCounterproposal(Flight f,LocalDateTime departure){if(departure==null)throw bad("La fecha y hora propuesta son obligatorias");if(Boolean.TRUE.equals(f.getExtremaUrgencia())&&departure.isAfter(f.getFechaLimiteTraslado()))throw bad("La contrapropuesta no puede superar el horario límite de extrema urgencia");}
 private FlightScheduleNegotiation lastCounterproposal(Flight f){return negotiations.findByFlightIdOrderByFechaOcurrenciaAsc(f.getId()).stream().filter(n->"CO_CONTRAPROPUESTA".equals(n.getTipo())).reduce((a,b)->b).orElseThrow(()->bad("No existe una contrapropuesta pendiente"));}
 private void negotiation(Flight f,String type,LocalDateTime time,String reason,User actor){FlightScheduleNegotiation n=new FlightScheduleNegotiation();n.setFlight(f);n.setTipo(type);n.setFechaHoraPropuesta(time);n.setMotivo(reason);n.setActor(actor);negotiations.save(n);}
 private void assertNoOverlap(Flight f){boolean conflict=flights.overlappingAircraft(f.getAircraft().getId(),f.getFechaPlanificadaSalida(),f.getFechaPlanificadaLlegada()).stream().anyMatch(x->!x.getId().equals(f.getId()))||flights.overlappingCommander(f.getComandante().getId(),f.getFechaPlanificadaSalida(),f.getFechaPlanificadaLlegada()).stream().anyMatch(x->!x.getId().equals(f.getId()));if(conflict)throw new ApiException(HttpStatus.CONFLICT,"Existe una asignación con horario incompatible");}
 private Locality locality(UUID id,String label){return localities.findByIdAndActivoTrue(id).orElseThrow(()->bad("Seleccione una localidad de "+label+" válida."));} private Airport activeAirport(UUID id,String label){Airport a=airports.findById(id).orElseThrow(()->notFound("Aeropuerto "+label));if(!Boolean.TRUE.equals(a.getActivo())||a.getProvinciaReferencial()==null)throw bad("El aeropuerto "+label+" debe estar activo y normalizado por provincia");return a;} private UUID provinceId(Airport a){return a.getProvinciaReferencial().getId();} private UUID originProvince(Flight f){return f.getLocalidadOrigenSolicitada().getProvincia().getId();} private UUID destinationProvince(Flight f){return f.getLocalidadDestinoSolicitada().getProvincia().getId();}
 private void ensureMutable(Flight f){if(Set.of("FINALIZADO","COMPLETADO","CANCELADO").contains(f.getStatus().getCodigo()))throw bad("El vuelo cerrado no admite modificaciones");} private void requireCommander(Flight f,UUID id){if(f.getComandante()==null||!f.getComandante().getId().equals(id))throw new ApiException(HttpStatus.FORBIDDEN,"Sólo el comandante asignado puede realizar esta operación");} private void requireStatus(Flight f,String s){if(!s.equals(f.getStatus().getCodigo()))throw bad("Transición no permitida desde "+f.getStatus().getCodigo());} private void requireOperations(UUID id){if(!hasOperationsRole(user(id)))throw new ApiException(HttpStatus.FORBIDDEN,"Sólo Centro de Operaciones puede ejecutar esta transición");} private User user(UUID id){return users.findById(id).orElseThrow(()->notFound("Usuario"));} private Flight locked(UUID id){return flights.lockById(id).orElseThrow(()->notFound("Vuelo"));} private FlightStatus status(String c){return statuses.findByCodigo(c).orElseThrow(()->new IllegalStateException("Catálogo de estados incompleto"));} private FlightPriority priority(String c){return priorities.findByCodigoAndActivoTrue(c).orElseThrow(()->bad("Prioridad inexistente o inactiva"));} private boolean hasRole(User u,String code){return users.findWithRolesByUsername(u.getUsername()).orElseThrow().getUserRoles().stream().anyMatch(x->code.equals(x.getRole().getCodigo()));} private boolean hasOperationsRole(User u){return hasRole(u,"OPERACIONES")||hasRole(u,"CENTRO_OPERACIONES");} private ApiException bad(String m){return new ApiException(HttpStatus.BAD_REQUEST,m);} private ApiException notFound(String m){return new ApiException(HttpStatus.NOT_FOUND,m+" inexistente");} private String requiredReason(String v,String message){if(v==null||v.isBlank())throw bad(message);return v.trim();} private String json(String value){return value==null?"null":"\""+value.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n").replace("\r","\\r")+"\"";}
 private LocalityView localityView(Locality l){return l==null?null:new LocalityView(l.getId(),l.getNombre(),l.getProvincia().getNombre(),l.getProvincia().getId());} private AvailableAircraftView aircraftView(Aircraft a){return new AvailableAircraftView(a.getId(),a.getMatricula(),a.getModelo(),a.getTipo(),a.getAeropuertoActual().getId(),a.getAeropuertoActual().getNombre());} private AvailableCommanderView commanderView(User u){CommanderProfile p=u.getPerson().getCommanderProfile();return new AvailableCommanderView(u.getId(),u.getUsername(),u.getPerson().getNombre(),u.getPerson().getApellido(),p.getLicenseNumber(),p.getProvinciaActual().getNombre());}
 private FlightView view(Flight f){var p=f.getPatient().getPerson();return new FlightView(f.getId(),f.getCodigo(),f.getStatus().getCodigo(),f.getPatient().getId(),p.getNombre()+" "+p.getApellido(),f.getPriority()==null?null:f.getPriority().getCodigo(),localityView(f.getLocalidadOrigenSolicitada()),localityView(f.getLocalidadDestinoSolicitada()),f.getFechaSolicitada(),Boolean.TRUE.equals(f.getExtremaUrgencia()),f.getJustificacionExtremaUrgencia(),f.getFechaLimiteTraslado(),f.getFechaPlanificadaSalida(),f.getFechaPlanificadaLlegada());}
 private FlightDetailView detail(Flight f){var patient=f.getPatient();var person=patient.getPerson();var info=medical.findByFlightId(f.getId()).orElse(null);var commander=f.getComandante();var profile=commander==null?null:commander.getPerson().getCommanderProfile();var plane=f.getAircraft();var timeline=negotiations.findByFlightIdOrderByFechaOcurrenciaAsc(f.getId()).stream().map(n->new NegotiationEventView(n.getTipo(),n.getFechaHoraPropuesta(),n.getMotivo(),n.getActor()==null?"Sistema":n.getActor().getUsername(),n.getFechaOcurrencia())).toList();return new FlightDetailView(view(f),new PatientDetail(patient.getId(),person.getNombre(),person.getApellido(),person.getDni()),info==null?null:new Medical(info.getDiagnostico(),info.getCondicionMedica(),Boolean.TRUE.equals(info.getRequiereEquipamientoEspecial()),info.getObservaciones()),f.getMotivoSolicitud(),f.getMotivoRechazo(),new ResourceAssignment(plane==null?null:plane.getId(),plane==null?null:plane.getMatricula(),commander==null?null:commander.getId(),commander==null?null:commander.getUsername(),commander==null?null:commander.getPerson().getNombre(),commander==null?null:commander.getPerson().getApellido(),profile==null?null:profile.getLicenseNumber(),profile==null||profile.getProvinciaActual()==null?null:profile.getProvinciaActual().getNombre()),timeline);}
}
