package db.migration;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.*;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.sql.*;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

/** Seeds versioned, local catalog snapshots; it never calls an external service. */
public class V16__seed_catalogos_geograficos extends BaseJavaMigration {
 private final ObjectMapper json=new ObjectMapper();
 @Override public void migrate(Context context) throws Exception {Connection c=context.getConnection();relaxLegacyAirportUniqueConstraints(c);seedProvinces(c);seedLocalities(c);seedAerodromes(c);migrateLegacyFlights(c);}
 /** SQL Server unique constraints treat NULL as a value; catalogue rows legitimately lack ICAO/IATA. */
 private void relaxLegacyAirportUniqueConstraints(Connection c)throws SQLException{String query="SELECT kc.name FROM sys.key_constraints kc JOIN sys.index_columns ic ON ic.object_id=kc.parent_object_id AND ic.index_id=kc.unique_index_id JOIN sys.columns col ON col.object_id=ic.object_id AND col.column_id=ic.column_id WHERE kc.parent_object_id=OBJECT_ID(N'dbo.aeropuertos') AND col.name IN ('codigo_oaci','codigo_iata')";try(Statement select=c.createStatement();ResultSet rows=select.executeQuery(query);Statement drop=c.createStatement()){while(rows.next()){String name=rows.getString(1).replace("]","]]" );drop.execute("ALTER TABLE aeropuertos DROP CONSTRAINT ["+name+"]");}}}
 private void seedProvinces(Connection c)throws Exception{JsonNode root=read("catalogos/provincias-georef-2026-09-28.json");try(PreparedStatement s=c.prepareStatement("INSERT INTO provincias(codigo_oficial,nombre) VALUES(?,?)")){for(JsonNode x:root.path("provincias")){s.setString(1,x.path("id").asText());s.setString(2,x.path("nombre").asText());s.addBatch();}s.executeBatch();}}
 private void seedLocalities(Connection c)throws Exception{JsonNode root=read("catalogos/localidades-georef-2026-09-28.json");try(PreparedStatement s=c.prepareStatement("INSERT INTO localidades(codigo_oficial,nombre,provincia_id) SELECT ?,?,id FROM provincias WHERE codigo_oficial=?")){int n=0;for(JsonNode x:root.path("localidades")){s.setString(1,x.path("id").asText());s.setString(2,x.path("nombre").asText());s.setString(3,x.path("provincia").path("id").asText());s.addBatch();if(++n%500==0)s.executeBatch();}s.executeBatch();}}
 private void seedAerodromes(Connection c)throws Exception{String sql="INSERT INTO aeropuertos(codigo_oficial,codigo_oaci,codigo_iata,nombre,ciudad,provincia,pais,latitud,longitud,activo,provincia_id,tipo) SELECT ?,?,?,?,?,?,N'Argentina',?,?,1,id,? FROM provincias p WHERE (p.nombre COLLATE Latin1_General_100_CI_AI=? COLLATE Latin1_General_100_CI_AI OR p.codigo_oficial=?) AND NOT EXISTS(SELECT 1 FROM aeropuertos a WHERE a.codigo_oficial=? OR (a.codigo_oaci IS NOT NULL AND a.codigo_oaci=?) OR (a.codigo_iata IS NOT NULL AND a.codigo_iata=?))";try(BufferedReader r=new BufferedReader(new InputStreamReader(resource("catalogos/aerodromos-mintrans-2026-09-28.csv"),StandardCharsets.UTF_8));PreparedStatement s=c.prepareStatement(sql)){r.readLine();String line;int n=0;while((line=r.readLine())!=null){String[] a=parseCsv(line);if(a.length<22||!"AERÓDROMO".equalsIgnoreCase(unquote(a[3])))continue;String code=blank(a[0]),oaci=blank(a[1]),iata=blank(a[2]),province=unquote(a[21]);s.setString(1,code);s.setString(2,oaci);s.setString(3,iata);s.setString(4,unquote(a[4]));s.setString(5,unquote(a[10]));s.setString(6,province);s.setBigDecimal(7,num(a[7]));s.setBigDecimal(8,num(a[6]));s.setString(9,"AERÓDROMO");s.setString(10,province);s.setString(11,province.startsWith("TIERRA DEL FUEGO")?"94":"");s.setString(12,code);s.setString(13,oaci);s.setString(14,iata);s.addBatch();if(++n%200==0)s.executeBatch();}s.executeBatch();}}
 /** Maps old free text only when it identifies exactly one official locality; ambiguous text remains legacy. */
 private void migrateLegacyFlights(Connection c)throws SQLException{String normalized="UPPER(LTRIM(RTRIM(v.%s))) COLLATE Latin1_General_100_CI_AI = UPPER(LTRIM(RTRIM(l.nombre))) COLLATE Latin1_General_100_CI_AI";migrateColumn(c,"localidad_origen_id","ciudad_origen_solicitada",normalized);migrateColumn(c,"localidad_destino_id","ciudad_destino_solicitada",normalized);}
 private void migrateColumn(Connection c,String target,String legacy,String normalized)throws SQLException{String match=normalized.formatted(legacy);String sql="UPDATE v SET "+target+"=(SELECT MIN(l.id) FROM localidades l WHERE "+match+") FROM vuelos v WHERE v."+target+" IS NULL AND v."+legacy+" IS NOT NULL AND (SELECT COUNT(*) FROM localidades l WHERE "+match+")=1";try(Statement s=c.createStatement()){s.executeUpdate(sql);}}
 private JsonNode read(String p)throws Exception{return json.readTree(resource(p));} private InputStream resource(String p){InputStream in=getClass().getClassLoader().getResourceAsStream(p);if(in==null)throw new IllegalStateException("Dataset faltante: "+p);return in;} private String blank(String v){v=unquote(v);return v.isBlank()?null:v;} private String unquote(String v){return v.replaceAll("^\\\"|\\\"$","").replace("\"\"","\"").trim();} private BigDecimal num(String v){try{return new BigDecimal(v.trim());}catch(Exception e){return null;}}
 private String[] parseCsv(String line){java.util.ArrayList<String> fields=new java.util.ArrayList<>();StringBuilder value=new StringBuilder();boolean quoted=false;for(int i=0;i<line.length();i++){char ch=line.charAt(i);if(ch=='\"'){if(quoted&&i+1<line.length()&&line.charAt(i+1)=='\"'){value.append(ch);i++;}else quoted=!quoted;}else if(ch==';'&&!quoted){fields.add(value.toString());value.setLength(0);}else value.append(ch);}fields.add(value.toString());return fields.toArray(String[]::new);}
}
